import type { Account, ContentItem, Question, RoleId } from "./types";

export const ACCOUNTS: Record<RoleId, Account> = {
  teacher: {
    id: "teacher",
    name: "Nguyễn Văn A",
    shortName: "NA",
    accountType: "Cá nhân",
    verified: "none",
    avatarColor: "#F59E0B",
    bio: "Giáo viên Toán - THCS Lý Thường Kiệt",
    followers: 124,
  },
  verified_teacher: {
    id: "verified_teacher",
    name: "TS. Trần Thị B",
    shortName: "TB",
    accountType: "Cá nhân",
    verified: "L2",
    avatarColor: "#2563EB",
    bio: "Tiến sĩ Vật lý - Đại học Sư phạm Hà Nội. Chuyên gia bồi dưỡng học sinh giỏi.",
    followers: 8420,
  },
  publisher: {
    id: "publisher",
    name: "NXB Giáo dục VN",
    shortName: "GD",
    accountType: "Doanh nghiệp",
    verified: "L2",
    avatarColor: "#20447E",
    bio: "Nhà xuất bản Giáo dục Việt Nam - Đơn vị xuất bản học liệu chính thống.",
    followers: 25340,
  },
  admin: {
    id: "admin",
    name: "Admin Hệ thống",
    shortName: "AD",
    accountType: "Admin",
    verified: "admin",
    avatarColor: "#EF4444",
    bio: "Quản trị viên hệ thống GK Studio.",
    followers: 0,
  },
};

export const SEED_CONTENT: ContentItem[] = [
  {
    id: "c1",
    title: "Ôn tập Đại số chương 1 - Lớp 8",
    type: "quiz",
    status: "published",
    ownerId: "verified_teacher",
    createdAt: "2026-05-28",
    views: 4218,
    likes: 312,
    shares: 41,
    thumbnailColor: "#2563EB",
    subject: "Toán",
    grade: "Lớp 8",
    platforms: ["national", "ebooks"],
    tags: ["Đại số", "Ôn tập", "Lớp 8"],
    description: "Bộ đề ôn tập kiến thức Đại số chương 1.",
  },
  {
    id: "c2",
    title: "Bài giảng: Dao động điều hòa",
    type: "material",
    status: "published",
    ownerId: "verified_teacher",
    createdAt: "2026-05-20",
    views: 2890,
    likes: 198,
    shares: 33,
    thumbnailColor: "#20447E",
    subject: "Vật lý",
    grade: "Lớp 11",
    platforms: ["national"],
    tags: ["Vật lý", "Dao động"],
    description: "Bài giảng đầy đủ về dao động điều hòa.",
  },
  {
    id: "c3",
    title: "Đề kiểm tra giữa kỳ Hóa học 10",
    type: "quiz",
    status: "pending",
    ownerId: "teacher",
    createdAt: "2026-06-02",
    views: 0,
    likes: 0,
    shares: 0,
    thumbnailColor: "#10B981",
    subject: "Hóa học",
    grade: "Lớp 10",
    platforms: ["national"],
    tags: ["Hóa", "Kiểm tra"],
    description: "Đề kiểm tra 45 phút giữa kỳ.",
  },
  {
    id: "c4",
    title: "Sách Tiếng Anh 12 - Unit 3",
    type: "material",
    status: "published",
    ownerId: "publisher",
    createdAt: "2026-04-15",
    views: 12450,
    likes: 890,
    shares: 145,
    thumbnailColor: "#F59E0B",
    subject: "Tiếng Anh",
    grade: "Lớp 12",
    platforms: ["national", "ebooks"],
    tags: ["English", "Unit 3"],
    description: "Học liệu chính thống Unit 3 - Tiếng Anh 12.",
  },
  {
    id: "c5",
    title: "Nháp: Đề thi học kỳ Sinh học",
    type: "quiz",
    status: "draft",
    ownerId: "teacher",
    createdAt: "2026-06-05",
    views: 0,
    likes: 0,
    shares: 0,
    thumbnailColor: "#EF4444",
    subject: "Sinh học",
    grade: "Lớp 9",
    platforms: [],
    tags: [],
    description: "",
  },
  {
    id: "c6",
    title: "Lịch sử Việt Nam thế kỷ XX",
    type: "material",
    status: "pending",
    ownerId: "teacher",
    createdAt: "2026-06-01",
    views: 0,
    likes: 0,
    shares: 0,
    thumbnailColor: "#8B5CF6",
    subject: "Lịch sử",
    grade: "Lớp 12",
    platforms: ["national"],
    tags: ["Lịch sử", "Việt Nam"],
    description: "Bài giảng tổng quan Lịch sử VN.",
  },
  {
    id: "c7",
    title: "Đề luyện thi THPT QG - Toán",
    type: "quiz",
    status: "rejected",
    ownerId: "teacher",
    createdAt: "2026-05-12",
    views: 0,
    likes: 0,
    shares: 0,
    thumbnailColor: "#717680",
    subject: "Toán",
    grade: "Lớp 12",
    platforms: ["national"],
    tags: ["THPT QG"],
    description: "Nội dung chưa đủ chuẩn — cần bổ sung lời giải.",
  },
  {
    id: "c8",
    title: "Atlas Địa lý Việt Nam tương tác",
    type: "material",
    status: "published",
    ownerId: "publisher",
    createdAt: "2026-03-20",
    views: 8920,
    likes: 654,
    shares: 89,
    thumbnailColor: "#10B981",
    subject: "Địa lý",
    grade: "Lớp 9",
    platforms: ["ebooks"],
    tags: ["Địa lý", "Atlas"],
    description: "Atlas tương tác bản đồ Việt Nam.",
  },
  {
    id: "c9",
    title: "Bộ đề Vật lý 11 - Chương Điện học",
    type: "quiz",
    status: "draft",
    ownerId: "verified_teacher",
    createdAt: "2026-06-07",
    views: 0,
    likes: 0,
    shares: 0,
    thumbnailColor: "#2563EB",
    subject: "Vật lý",
    grade: "Lớp 11",
    platforms: [],
    tags: [],
    description: "",
  },
  {
    id: "c10",
    title: "Học liệu: Văn học dân gian",
    type: "material",
    status: "published",
    ownerId: "verified_teacher",
    createdAt: "2026-04-30",
    views: 3210,
    likes: 245,
    shares: 28,
    thumbnailColor: "#F59E0B",
    subject: "Ngữ văn",
    grade: "Lớp 10",
    platforms: ["national"],
    tags: ["Văn học", "Dân gian"],
    description: "Tổng hợp văn học dân gian Việt Nam.",
  },
];

export const SAMPLE_QUESTIONS: Question[] = [
  {
    id: "q1",
    type: "multiple_choice",
    prompt: "Phương trình nào sau đây là phương trình bậc nhất một ẩn?",
    options: [
      { id: "a", text: "2x + 3 = 0" },
      { id: "b", text: "x² - 4 = 0" },
      { id: "c", text: "x³ + x = 1" },
      { id: "d", text: "2x + y = 5" },
    ],
    correctOptionId: "a",
    duration: 30,
    points: 1,
    required: true,
  },
  {
    id: "q2",
    type: "drag_drop",
    prompt: "Ghép cặp đại lượng vật lý với đơn vị đo:",
    pairs: [
      { id: "p1", left: "Lực", right: "Newton (N)" },
      { id: "p2", left: "Năng lượng", right: "Joule (J)" },
      { id: "p3", left: "Công suất", right: "Watt (W)" },
    ],
    duration: 60,
    points: 2,
    required: true,
  },
  {
    id: "q3",
    type: "essay",
    prompt: "Trình bày định luật bảo toàn năng lượng và cho một ví dụ minh họa.",
    essayAnswer: "",
    duration: 300,
    points: 5,
    required: false,
  },
];

export const ANALYTICS_30D = Array.from({ length: 30 }, (_, i) => ({
  date: `Ngày ${i + 1}`,
  views: Math.round(200 + Math.sin(i / 3) * 80 + Math.random() * 120),
}));

export const ANALYTICS_7D = ANALYTICS_30D.slice(-7);
export const ANALYTICS_90D = Array.from({ length: 90 }, (_, i) => ({
  date: `N${i + 1}`,
  views: Math.round(180 + Math.sin(i / 5) * 100 + Math.random() * 150),
}));