import type {
  Account,
  ContentItem,
  ContentReport,
  Question,
  RoleId,
  VerificationRequest,
} from "./types";

export const ACCOUNTS: Record<RoleId, Account> = {
  teacher: {
    id: "teacher",
    name: "Nguyễn Văn A",
    shortName: "NA",
    accountType: "Cá nhân",
    verified: "none",
    avatarColor: "#F59E0B",
    bio: "Giáo viên Toán - THCS Lý Thường Kiệt",
    followers: 124,
    website: "https://thaygiaotoan.vn",
    email: "nguyenvana@thcs-ltk.edu.vn",
    orgMemberships: [
      {
        orgId: "publisher",
        orgName: "NXB Giáo dục VN",
        orgShortName: "GD",
        orgColor: "#20447E",
        role: "editor",
      },
    ],
  },
  verified_teacher: {
    id: "verified_teacher",
    name: "TS. Trần Thị B",
    shortName: "TB",
    accountType: "Cá nhân",
    verified: "L2",
    avatarColor: "#2563EB",
    bio: "Tiến sĩ Vật lý - Đại học Sư phạm Hà Nội. Chuyên gia bồi dưỡng học sinh giỏi.",
    followers: 8420,
    website: "https://tranthib.edu.vn",
    email: "tranthib@hnue.edu.vn",
    orgMemberships: [
      {
        orgId: "publisher",
        orgName: "NXB Giáo dục VN",
        orgShortName: "GD",
        orgColor: "#20447E",
        role: "manager",
      },
    ],
  },
  publisher: {
    id: "publisher",
    name: "NXB Giáo dục VN",
    shortName: "GD",
    accountType: "Doanh nghiệp",
    verified: "L2",
    avatarColor: "#20447E",
    bio: "Nhà xuất bản Giáo dục Việt Nam - Đơn vị xuất bản học liệu chính thống.",
    followers: 25340,
    website: "https://nxbgd.vn",
    email: "lienhe@nxbgd.vn",
    businessLicense: "GP-XB-0123/NXBGD",
    managers: [
      { email: "owner@nxbgd.vn", name: "Lê Quốc Owner", role: "owner", joinedAt: "2025-09-01" },
      {
        email: "manager1@nxbgd.vn",
        name: "Phạm Thu Manager",
        role: "manager",
        joinedAt: "2025-10-12",
      },
      {
        email: "editor1@nxbgd.vn",
        name: "Đỗ Văn Editor",
        role: "editor",
        joinedAt: "2025-11-03",
      },
      {
        email: "editor2@nxbgd.vn",
        name: "Vũ Thị Biên Tập",
        role: "editor",
        joinedAt: "2026-01-20",
      },
    ],
  },
  admin: {
    id: "admin",
    name: "Admin Hệ thống",
    shortName: "AD",
    accountType: "Admin",
    verified: "admin",
    avatarColor: "#EF4444",
    bio: "Quản trị viên hệ thống GK Studio.",
    followers: 0,
  },
};

export const SEED_CONTENT: ContentItem[] = [
  {
    id: "c1",
    title: "Ôn tập Đại số chương 1 - Lớp 8",
    type: "learning_material",
    legacyType: "quiz",
    category: "learning_material",
    materialSubtype: "quiz",
    status: "published",
    ownerId: "verified_teacher",
    ownerName: "TS. Trần Thị B",
    createdAt: "2026-05-28",
    views: 4218,
    likes: 312,
    shares: 41,
    thumbnailColor: "#2563EB",
    subject: "Toán",
    grade: "Lớp 8",
    platforms: ["national", "ebooks"],
    tags: ["Đại số", "Ôn tập", "Lớp 8"],
    description: "Bộ đề ôn tập kiến thức Đại số chương 1.",
  },
  {
    id: "c2",
    title: "Bài giảng: Dao động điều hòa",
    type: "learning_material",
    legacyType: "material",
    category: "learning_material",
    materialSubtype: "lesson",
    status: "published",
    ownerId: "verified_teacher",
    ownerName: "TS. Trần Thị B",
    createdAt: "2026-05-20",
    views: 2890,
    likes: 198,
    shares: 33,
    thumbnailColor: "#20447E",
    subject: "Vật lý",
    grade: "Lớp 11",
    platforms: ["national"],
    tags: ["Vật lý", "Dao động"],
    description: "Bài giảng đầy đủ về dao động điều hòa.",
    fileName: "dao-dong-dieu-hoa.pptx",
    fileExtension: "pptx",
  },
  {
    id: "c3",
    title: "Đề kiểm tra giữa kỳ Hóa học 10",
    type: "learning_material",
    legacyType: "quiz",
    category: "learning_material",
    materialSubtype: "quiz",
    status: "pending",
    ownerId: "teacher",
    ownerName: "Nguyễn Văn A",
    createdAt: "2026-06-02",
    views: 0,
    likes: 0,
    shares: 0,
    thumbnailColor: "#10B981",
    subject: "Hóa học",
    grade: "Lớp 10",
    platforms: ["national"],
    tags: ["Hóa", "Kiểm tra"],
    description: "Đề kiểm tra 45 phút giữa kỳ.",
  },
  {
    id: "c4",
    title: "Sách Tiếng Anh 12 - Unit 3",
    type: "book",
    legacyType: "material",
    category: "book",
    materialType: "book",
    status: "published",
    ownerId: "publisher",
    ownerName: "Đỗ Văn Editor",
    createdAt: "2026-04-15",
    views: 12450,
    likes: 890,
    shares: 145,
    thumbnailColor: "#F59E0B",
    subject: "Tiếng Anh",
    grade: "Lớp 12",
    platforms: ["national", "ebooks"],
    tags: ["English", "Unit 3"],
    description: "Học liệu chính thống Unit 3 - Tiếng Anh 12.",
  },
  {
    id: "c5",
    title: "Nháp: Đề thi học kỳ Sinh học",
    type: "learning_material",
    legacyType: "quiz",
    category: "learning_material",
    materialSubtype: "quiz",
    status: "draft",
    ownerId: "teacher",
    ownerName: "Nguyễn Văn A",
    createdAt: "2026-06-05",
    views: 0,
    likes: 0,
    shares: 0,
    thumbnailColor: "#EF4444",
    subject: "Sinh học",
    grade: "Lớp 9",
    platforms: [],
    tags: [],
    description: "",
  },
  {
    id: "c6",
    title: "Khóa học: Lịch sử Việt Nam thế kỷ XX",
    type: "course",
    legacyType: "material",
    category: "course",
    materialType: "course",
    status: "pending",
    ownerId: "teacher",
    ownerName: "Nguyễn Văn A",
    createdAt: "2026-06-01",
    views: 0,
    likes: 0,
    shares: 0,
    thumbnailColor: "#8B5CF6",
    subject: "Lịch sử",
    grade: "Lớp 12",
    platforms: ["national"],
    tags: ["Lịch sử", "Việt Nam"],
    description: "Lộ trình học tổng quan Lịch sử VN.",
  },
  {
    id: "c7",
    title: "Đề luyện thi THPT QG - Toán",
    type: "learning_material",
    legacyType: "quiz",
    category: "learning_material",
    materialSubtype: "quiz",
    status: "rejected",
    ownerId: "teacher",
    ownerName: "Nguyễn Văn A",
    createdAt: "2026-05-12",
    views: 0,
    likes: 0,
    shares: 0,
    thumbnailColor: "#717680",
    subject: "Toán",
    grade: "Lớp 12",
    platforms: ["national"],
    tags: ["THPT QG"],
    description: "Nội dung chưa đủ chuẩn — cần bổ sung lời giải.",
  },
  {
    id: "c8",
    title: "Atlas Địa lý Việt Nam tương tác",
    type: "learning_material",
    legacyType: "material",
    category: "learning_material",
    materialSubtype: "3d_vr",
    status: "published",
    ownerId: "publisher",
    ownerName: "Phạm Thu Manager",
    createdAt: "2026-03-20",
    views: 8920,
    likes: 654,
    shares: 89,
    thumbnailColor: "#10B981",
    subject: "Địa lý",
    grade: "Lớp 9",
    platforms: ["ebooks"],
    tags: ["Địa lý", "Atlas"],
    description: "Atlas tương tác bản đồ Việt Nam.",
    fileName: "atlas-vn.glb",
    fileExtension: "glb",
  },
  {
    id: "c9",
    title: "Bộ đề Vật lý 11 - Chương Điện học",
    type: "learning_material",
    legacyType: "quiz",
    category: "learning_material",
    materialSubtype: "quiz",
    status: "draft",
    ownerId: "verified_teacher",
    ownerName: "TS. Trần Thị B",
    createdAt: "2026-06-07",
    views: 0,
    likes: 0,
    shares: 0,
    thumbnailColor: "#2563EB",
    subject: "Vật lý",
    grade: "Lớp 11",
    platforms: [],
    tags: [],
    description: "",
  },
  {
    id: "c10",
    title: "Tài liệu: Văn học dân gian",
    type: "learning_material",
    legacyType: "material",
    category: "learning_material",
    materialSubtype: "document",
    status: "published",
    ownerId: "verified_teacher",
    ownerName: "TS. Trần Thị B",
    createdAt: "2026-04-30",
    views: 3210,
    likes: 245,
    shares: 28,
    thumbnailColor: "#F59E0B",
    subject: "Ngữ văn",
    grade: "Lớp 10",
    platforms: ["national"],
    tags: ["Văn học", "Dân gian"],
    description: "Tổng hợp văn học dân gian Việt Nam.",
    fileName: "van-hoc-dan-gian.pdf",
    fileExtension: "pdf",
  },
  {
    id: "c11",
    title: "Video bài giảng: Quang hợp ở thực vật",
    type: "learning_material",
    legacyType: "material",
    category: "learning_material",
    materialSubtype: "video",
    status: "published",
    ownerId: "verified_teacher",
    ownerName: "TS. Trần Thị B",
    createdAt: "2026-05-02",
    views: 5640,
    likes: 421,
    shares: 67,
    thumbnailColor: "#10B981",
    subject: "Sinh học",
    grade: "Lớp 11",
    platforms: ["national", "ebooks"],
    tags: ["Sinh học", "Quang hợp"],
    description: "Video minh họa quá trình quang hợp.",
    fileName: "quang-hop.mp4",
    fileExtension: "mp4",
  },
  {
    id: "c12",
    title: "Infographic: Bảng tuần hoàn hóa học",
    type: "learning_material",
    legacyType: "material",
    category: "learning_material",
    materialSubtype: "image",
    status: "published",
    ownerId: "publisher",
    ownerName: "Vũ Thị Biên Tập",
    createdAt: "2026-04-18",
    views: 7120,
    likes: 512,
    shares: 98,
    thumbnailColor: "#2563EB",
    subject: "Hóa học",
    grade: "Lớp 10",
    platforms: ["ebooks"],
    tags: ["Hóa học", "Infographic"],
    description: "Bảng tuần hoàn các nguyên tố trực quan.",
    fileName: "bang-tuan-hoan.png",
    fileExtension: "png",
  },
  {
    id: "c13",
    title: "Audio luyện nghe Tiếng Anh 9",
    type: "learning_material",
    legacyType: "material",
    category: "learning_material",
    materialSubtype: "audio",
    status: "pending",
    ownerId: "publisher",
    ownerName: "Đỗ Văn Editor",
    createdAt: "2026-06-03",
    views: 0,
    likes: 0,
    shares: 0,
    thumbnailColor: "#F59E0B",
    subject: "Tiếng Anh",
    grade: "Lớp 9",
    platforms: ["national"],
    tags: ["English", "Listening"],
    description: "Bộ audio luyện kỹ năng nghe.",
    fileName: "listening-unit5.mp3",
    fileExtension: "mp3",
  },
  {
    id: "c14",
    title: "Gói SCORM: Mô phỏng mạch điện",
    type: "learning_material",
    legacyType: "material",
    category: "learning_material",
    materialSubtype: "scorm",
    status: "published",
    ownerId: "publisher",
    ownerName: "Phạm Thu Manager",
    createdAt: "2026-03-28",
    views: 2310,
    likes: 156,
    shares: 22,
    thumbnailColor: "#8B5CF6",
    subject: "Vật lý",
    grade: "Lớp 9",
    platforms: ["national", "ebooks"],
    tags: ["SCORM", "Mạch điện"],
    description: "Gói SCORM tích hợp LMS mô phỏng mạch điện.",
    fileName: "mach-dien-scorm.zip",
    fileExtension: "zip",
  },
  {
    id: "c15",
    title: "Học liệu nâng cao: Phòng thí nghiệm ảo Hóa",
    type: "learning_material",
    legacyType: "material",
    category: "learning_material",
    materialSubtype: "advanced",
    status: "published",
    ownerId: "publisher",
    ownerName: "Vũ Thị Biên Tập",
    createdAt: "2026-02-14",
    views: 4015,
    likes: 289,
    shares: 54,
    thumbnailColor: "#10B981",
    subject: "Hóa học",
    grade: "Lớp 11",
    platforms: ["ebooks"],
    tags: ["Lab ảo", "HTML5"],
    description: "Phòng thí nghiệm ảo tương tác HTML5.",
    fileName: "lab-hoa.zip",
    fileExtension: "html",
  },
  {
    id: "c16",
    title: "Sách bài tập Toán nâng cao 9",
    type: "book",
    legacyType: "material",
    category: "book",
    materialType: "book",
    status: "draft",
    ownerId: "publisher",
    ownerName: "Đỗ Văn Editor",
    createdAt: "2026-06-06",
    views: 0,
    likes: 0,
    shares: 0,
    thumbnailColor: "#20447E",
    subject: "Toán",
    grade: "Lớp 9",
    platforms: [],
    tags: ["Toán", "Nâng cao"],
    description: "",
  },
  {
    id: "c17",
    title: "Giáo trình Ngữ văn 11 — Tập 1",
    type: "book",
    legacyType: "material",
    category: "book",
    materialType: "book",
    status: "published",
    ownerId: "publisher",
    ownerName: "Phạm Thu Manager",
    createdAt: "2026-03-10",
    views: 18200,
    likes: 1340,
    shares: 210,
    thumbnailColor: "#8B5CF6",
    subject: "Ngữ văn",
    grade: "Lớp 11",
    platforms: ["national", "ebooks"],
    tags: ["Ngữ văn", "Giáo trình"],
    description: "Giáo trình chính thức Ngữ văn 11 — Tập 1.",
  },
  {
    id: "c18",
    title: "Sách Toán 10 Cánh Diều",
    type: "book",
    legacyType: "material",
    category: "book",
    materialType: "book",
    status: "published",
    ownerId: "publisher",
    ownerName: "Lê Quốc Owner",
    createdAt: "2026-02-20",
    views: 22150,
    likes: 1780,
    shares: 320,
    thumbnailColor: "#2563EB",
    subject: "Toán",
    grade: "Lớp 10",
    platforms: ["national", "ebooks"],
    tags: ["Toán", "Cánh Diều"],
    description: "Sách giáo khoa Toán 10 bộ Cánh Diều.",
  },
  {
    id: "c19",
    title: "Khóa học: Lập trình Python cơ bản",
    type: "course",
    legacyType: "material",
    category: "course",
    materialType: "course",
    status: "published",
    ownerId: "verified_teacher",
    ownerName: "TS. Trần Thị B",
    createdAt: "2026-04-05",
    views: 9870,
    likes: 720,
    shares: 156,
    thumbnailColor: "#10B981",
    subject: "Tin học",
    grade: "Lớp 11",
    platforms: ["national", "ebooks"],
    tags: ["Python", "Lập trình"],
    description: "Khóa học lập trình Python từ cơ bản đến nâng cao.",
  },
  {
    id: "c20",
    title: "Khóa học: IELTS Writing Task 2",
    type: "course",
    legacyType: "material",
    category: "course",
    materialType: "course",
    status: "published",
    ownerId: "publisher",
    ownerName: "Đỗ Văn Editor",
    createdAt: "2026-05-08",
    views: 15340,
    likes: 1120,
    shares: 245,
    thumbnailColor: "#F59E0B",
    subject: "Tiếng Anh",
    grade: "Lớp 12",
    platforms: ["ebooks"],
    tags: ["IELTS", "Writing"],
    description: "Lộ trình chinh phục IELTS Writing Task 2.",
  },
  {
    id: "c21",
    title: "Bộ đề trắc nghiệm Sinh học 12",
    type: "learning_material",
    legacyType: "quiz",
    category: "learning_material",
    materialSubtype: "quiz",
    status: "published",
    ownerId: "verified_teacher",
    ownerName: "TS. Trần Thị B",
    createdAt: "2026-05-15",
    views: 6540,
    likes: 489,
    shares: 78,
    thumbnailColor: "#10B981",
    subject: "Sinh học",
    grade: "Lớp 12",
    platforms: ["national"],
    tags: ["Sinh học", "Trắc nghiệm"],
    description: "200 câu trắc nghiệm ôn thi TN THPT.",
  },
  {
    id: "c22",
    title: "Video: Thí nghiệm Vật lý - Lực đàn hồi",
    type: "learning_material",
    legacyType: "material",
    category: "learning_material",
    materialSubtype: "video",
    status: "published",
    ownerId: "teacher",
    ownerName: "Nguyễn Văn A",
    createdAt: "2026-05-22",
    views: 1820,
    likes: 134,
    shares: 19,
    thumbnailColor: "#EF4444",
    subject: "Vật lý",
    grade: "Lớp 10",
    platforms: ["national"],
    tags: ["Vật lý", "Thí nghiệm"],
    description: "Video thí nghiệm minh họa lực đàn hồi lò xo.",
    fileName: "luc-dan-hoi.mp4",
    fileExtension: "mp4",
  },
  {
    id: "c23",
    title: "Tài liệu: Công thức Hóa học THPT",
    type: "learning_material",
    legacyType: "material",
    category: "learning_material",
    materialSubtype: "document",
    status: "published",
    ownerId: "teacher",
    ownerName: "Nguyễn Văn A",
    createdAt: "2026-04-28",
    views: 2450,
    likes: 178,
    shares: 32,
    thumbnailColor: "#10B981",
    subject: "Hóa học",
    grade: "Lớp 12",
    platforms: ["national"],
    tags: ["Hóa học", "Công thức"],
    description: "Tổng hợp toàn bộ công thức Hóa THPT.",
    fileName: "cong-thuc-hoa.pdf",
    fileExtension: "pdf",
  },
  {
    id: "c24",
    title: "Bài giảng: Phép biến hình trong mặt phẳng",
    type: "learning_material",
    legacyType: "material",
    category: "learning_material",
    materialSubtype: "lesson",
    status: "published",
    ownerId: "verified_teacher",
    ownerName: "TS. Trần Thị B",
    createdAt: "2026-04-12",
    views: 3680,
    likes: 267,
    shares: 45,
    thumbnailColor: "#8B5CF6",
    subject: "Toán",
    grade: "Lớp 11",
    platforms: ["national", "ebooks"],
    tags: ["Toán", "Hình học"],
    description: "Bài giảng chi tiết về phép tịnh tiến, đối xứng, quay.",
    fileName: "phep-bien-hinh.pptx",
    fileExtension: "pptx",
  },
  {
    id: "c25",
    title: "Đề kiểm tra 15 phút - Toán 8",
    type: "learning_material",
    legacyType: "quiz",
    category: "learning_material",
    materialSubtype: "quiz",
    status: "published",
    ownerId: "teacher",
    ownerName: "Nguyễn Văn A",
    createdAt: "2026-05-30",
    views: 890,
    likes: 45,
    shares: 8,
    thumbnailColor: "#F59E0B",
    subject: "Toán",
    grade: "Lớp 8",
    platforms: ["national"],
    tags: ["Toán", "Kiểm tra"],
    description: "Đề kiểm tra nhanh 15 phút chương Hình học.",
  },
  {
    id: "c26",
    title: "Hình ảnh: Sơ đồ tư duy Lịch sử VN",
    type: "learning_material",
    legacyType: "material",
    category: "learning_material",
    materialSubtype: "image",
    status: "published",
    ownerId: "teacher",
    ownerName: "Nguyễn Văn A",
    createdAt: "2026-05-18",
    views: 1560,
    likes: 112,
    shares: 24,
    thumbnailColor: "#8B5CF6",
    subject: "Lịch sử",
    grade: "Lớp 12",
    platforms: ["national"],
    tags: ["Lịch sử", "Sơ đồ tư duy"],
    description: "Sơ đồ tóm tắt các giai đoạn lịch sử VN.",
    fileName: "so-do-tu-duy-ls.png",
    fileExtension: "png",
  },
  {
    id: "c27",
    title: "Khóa ôn thi TN THPT Toán 2026",
    type: "course",
    legacyType: "material",
    category: "course",
    materialType: "course",
    status: "draft",
    ownerId: "verified_teacher",
    ownerName: "TS. Trần Thị B",
    createdAt: "2026-06-08",
    views: 0,
    likes: 0,
    shares: 0,
    thumbnailColor: "#2563EB",
    subject: "Toán",
    grade: "Lớp 12",
    platforms: [],
    tags: ["Toán", "THPT QG"],
    description: "",
  },
  {
    id: "c28",
    title: "Sách Khoa học tự nhiên 6",
    type: "book",
    legacyType: "material",
    category: "book",
    materialType: "book",
    status: "published",
    ownerId: "publisher",
    ownerName: "Vũ Thị Biên Tập",
    createdAt: "2026-01-15",
    views: 14780,
    likes: 1050,
    shares: 178,
    thumbnailColor: "#10B981",
    subject: "KHTN",
    grade: "Lớp 6",
    platforms: ["national", "ebooks"],
    tags: ["KHTN", "Lớp 6"],
    description: "Sách giáo khoa Khoa học tự nhiên 6.",
  },
];

export const VERIFICATION_REQUESTS: VerificationRequest[] = [
  {
    id: "vr1",
    applicantId: "teacher",
    accountType: "Cá nhân",
    status: "pending",
    submittedAt: "2026-06-08",
    documents: ["chung-chi-su-pham.pdf", "the-giao-vien.jpg"],
    materialsCount: 5,
    views: 620,
    accountAgeDays: 210,
  },
  {
    id: "vr2",
    applicantId: "publisher",
    accountType: "Doanh nghiệp",
    status: "pending",
    submittedAt: "2026-06-09",
    documents: ["giay-phep-xuat-ban.pdf", "quyet-dinh-thanh-lap.pdf"],
    materialsCount: 12,
    views: 64810,
    accountAgeDays: 285,
  },
];

export const CONTENT_REPORTS: ContentReport[] = [
  {
    id: "rp1",
    contentId: "c7",
    contentTitle: "Đề luyện thi THPT QG - Toán",
    reason: "inaccurate",
    reporterName: "Phụ huynh Lớp 12A",
    reportedAt: "2026-06-07",
    status: "open",
    note: "Đáp án câu 14 chưa chính xác.",
  },
  {
    id: "rp2",
    contentId: "c12",
    contentTitle: "Infographic: Bảng tuần hoàn hóa học",
    reason: "copyright",
    reporterName: "NXB Khác",
    reportedAt: "2026-06-05",
    status: "open",
    note: "Nghi ngờ vi phạm bản quyền hình ảnh.",
  },
  {
    id: "rp3",
    contentId: "c11",
    contentTitle: "Video bài giảng: Quang hợp ở thực vật",
    reason: "spam",
    reporterName: "Giáo viên ẩn danh",
    reportedAt: "2026-06-02",
    status: "open",
  },
];

export const SAMPLE_QUESTIONS: Question[] = [
  {
    id: "q1",
    type: "multiple_choice",
    prompt: "Phương trình nào sau đây là phương trình bậc nhất một ẩn?",
    options: [
      { id: "a", text: "2x + 3 = 0" },
      { id: "b", text: "x² - 4 = 0" },
      { id: "c", text: "x³ + x = 1" },
      { id: "d", text: "2x + y = 5" },
    ],
    correctOptionId: "a",
    duration: 30,
    points: 1,
    required: true,
  },
  {
    id: "q2",
    type: "drag_drop",
    prompt: "Ghép cặp đại lượng vật lý với đơn vị đo:",
    pairs: [
      { id: "p1", left: "Lực", right: "Newton (N)" },
      { id: "p2", left: "Năng lượng", right: "Joule (J)" },
      { id: "p3", left: "Công suất", right: "Watt (W)" },
    ],
    duration: 60,
    points: 2,
    required: true,
  },
  {
    id: "q3",
    type: "essay",
    prompt: "Trình bày định luật bảo toàn năng lượng và cho một ví dụ minh họa.",
    essayAnswer: "",
    duration: 300,
    points: 5,
    required: false,
  },
];

export const ANALYTICS_30D = Array.from({ length: 30 }, (_, i) => ({
  date: `Ngày ${i + 1}`,
  views: Math.round(200 + Math.sin(i / 3) * 80 + ((i * 53) % 120)),
}));

export const ANALYTICS_7D = ANALYTICS_30D.slice(-7);
export const ANALYTICS_90D = Array.from({ length: 90 }, (_, i) => ({
  date: `N${i + 1}`,
  views: Math.round(180 + Math.sin(i / 5) * 100 + ((i * 37) % 150)),
}));
