import type {
  Account,
  ContentItem,
  ContentReport,
  ContentTier,
  Question,
  RoleId,
  SchoolRole,
  VerificationRequest,
} from "./types";
import { generateRegistryId } from "./registry-id";

export const ACCOUNTS: Record<RoleId, Account> = {
  teacher: {
    id: "teacher",
    name: "Lê Trung Hiếu",
    shortName: "LH",
    accountType: "Cá nhân",
    verified: "none",
    avatarColor: "#F59E0B",
    bio: "Giáo viên Hóa học - THCS Lý Thường Kiệt",
    followers: 124,
    website: "https://thayhieu.vn",
    email: "letrunghieu@thcs-ltk.edu.vn",
    orgMemberships: [
      {
        orgId: "publisher",
        orgName: "NXB Giáo dục VN",
        orgShortName: "GD",
        orgColor: "#20447E",
        role: "editor",
      },
    ],
  },
  verified_teacher: {
    id: "verified_teacher",
    name: "Hoàng Xuân Nhi",
    shortName: "HN",
    accountType: "Cá nhân",
    verified: "L2",
    avatarColor: "#2563EB",
    bio: "Giáo viên Toán - THPT Chuyên Lê Hồng Phong. Chuyên gia bồi dưỡng học sinh giỏi.",
    followers: 8420,
    website: "https://conhi.edu.vn",
    email: "hoangxuannhi@lhp.edu.vn",
    orgMemberships: [
      {
        orgId: "publisher",
        orgName: "NXB Giáo dục VN",
        orgShortName: "GD",
        orgColor: "#20447E",
        role: "manager",
      },
    ],
  },
  publisher: {
    id: "publisher",
    name: "NXB Giáo dục VN",
    shortName: "GD",
    accountType: "Doanh nghiệp",
    verified: "L2",
    avatarColor: "#20447E",
    bio: "Nhà xuất bản Giáo dục Việt Nam - Đơn vị xuất bản học liệu chính thống.",
    followers: 25340,
    website: "https://nxbgd.vn",
    email: "lienhe@nxbgd.vn",
    businessLicense: "GP-XB-0123/NXBGD",
    managers: [
      { email: "owner@nxbgd.vn", name: "Đoàn Thuận Anh Thư", role: "owner", joinedAt: "2025-09-01" },
      {
        email: "manager1@nxbgd.vn",
        name: "Trần Thị Mai",
        role: "manager",
        joinedAt: "2025-10-12",
      },
      {
        email: "editor1@nxbgd.vn",
        name: "Vũ Đức Long",
        role: "editor",
        joinedAt: "2025-11-03",
      },
      {
        email: "editor2@nxbgd.vn",
        name: "Đỗ Quỳnh Chi",
        role: "editor",
        joinedAt: "2026-01-20",
      },
    ],
  },
  admin: {
    id: "admin",
    name: "Admin Trường học số Quốc gia",
    shortName: "AD",
    accountType: "Admin",
    verified: "admin",
    avatarColor: "#EF4444",
    bio: "Quản trị viên hệ thống GK Studio.",
    followers: 0,
  },
  reviewer: {
    id: "reviewer",
    name: "Hội đồng thẩm định Trường học số Quốc gia",
    shortName: "HĐ",
    accountType: "Admin",
    verified: "admin",
    avatarColor: "#20447E",
    bio: "Thành viên Hội đồng chuyên môn thẩm định học liệu quốc gia.",
    followers: 0,
    council: "Hội đồng Toán THPT",
  },
  student: {
    id: "student",
    name: "Nguyễn An",
    shortName: "NA",
    accountType: "Cá nhân",
    verified: "none",
    avatarColor: "#10B981",
    bio: "Học sinh lớp 10, đang học theo lộ trình cá nhân hoá.",
    followers: 0,
  },
  school: {
    id: "school",
    name: "THPT Lê Lợi",
    shortName: "LL",
    accountType: "Doanh nghiệp",
    verified: "L2",
    avatarColor: "#2563EB",
    bio: "Trường THPT Lê Lợi — quản lý dạy học số toàn trường.",
    followers: 0,
    schoolRole: "manager",
  },
};

export const TEACHER_DEPT_ACCOUNT: Account = {
  id: "teacher",
  name: "Tổ trưởng Tổ Toán",
  shortName: "TT",
  accountType: "Cá nhân",
  verified: "verified",
  avatarColor: "#F59E0B",
  bio: "Giáo viên kiêm tổ trưởng bộ môn Toán — duyệt học liệu cấp tổ.",
  followers: 0,
  schoolRole: "dept_head",
  subjectScope: "Toán",
};

export interface DemoLogin {
  key: string; // duy nhất cho tile login
  roleId: RoleId;
  schoolRole?: SchoolRole;
  account: Account;
  tagline: string; // mô tả ngắn vai trò trên tile
}

export const DEMO_LOGINS: DemoLogin[] = [
  { key: "admin", roleId: "admin", account: ACCOUNTS.admin, tagline: "Quản trị viên Bộ GD&ĐT" },
  { key: "reviewer", roleId: "reviewer", account: ACCOUNTS.reviewer, tagline: "Hội đồng thẩm định" },
  { key: "teacher", roleId: "teacher", account: ACCOUNTS.teacher, tagline: "Giáo viên" },
  { key: "teacher-dept", roleId: "teacher", schoolRole: "dept_head", account: TEACHER_DEPT_ACCOUNT, tagline: "Tổ trưởng bộ môn (Giáo viên)" },
  { key: "school", roleId: "school", schoolRole: "manager", account: ACCOUNTS.school, tagline: "Quản lý nhà trường" },
  { key: "publisher", roleId: "publisher", account: ACCOUNTS.publisher, tagline: "Đối tác nội dung (NXB/EdTech)" },
];

export const resolveDemoAccount = (roleId: RoleId, schoolRole?: SchoolRole): Account =>
  roleId === "teacher" && schoolRole === "dept_head" ? TEACHER_DEPT_ACCOUNT : ACCOUNTS[roleId];

// helper gán mã cho seed (chạy 1 lần khi định nghĩa SEED_CONTENT)
let _seq = 0;
const stamp = (tier: ContentTier, subject: string, year = 2026) =>
  generateRegistryId(tier, subject, ++_seq, year);

export const SEED_CONTENT: ContentItem[] = [
  {
    id: "c1",
    title: "Ôn tập Đại số chương 1 - Lớp 8",
    type: "learning_material",
    legacyType: "quiz",
    category: "learning_material",
    materialSubtype: "quiz",
    status: "published",
    ownerId: "verified_teacher",
    ownerName: "Hoàng Xuân Nhi",
    createdAt: "2026-05-28",
    views: 4218,
    likes: 312,
    shares: 41,
    thumbnailColor: "#2563EB",
    subject: "Toán",
    grade: "Lớp 8",
    platforms: ["national", "ebooks"],
    tags: ["Đại số", "Ôn tập", "Lớp 8"],
    description: "Bộ đề ôn tập kiến thức Đại số chương 1.",
    tier: "root",
    registryId: stamp("root", "Toán"),
    qualityLabel: "ministry_standard",
  },
  {
    id: "c2",
    title: "Bài giảng: Dao động điều hòa",
    type: "learning_material",
    legacyType: "material",
    category: "learning_material",
    materialSubtype: "lesson",
    status: "published",
    ownerId: "verified_teacher",
    ownerName: "Hoàng Xuân Nhi",
    createdAt: "2026-05-20",
    views: 2890,
    likes: 198,
    shares: 33,
    thumbnailColor: "#20447E",
    subject: "Vật lý",
    grade: "Lớp 11",
    platforms: ["national"],
    tags: ["Vật lý", "Dao động"],
    description: "Bài giảng đầy đủ về dao động điều hòa.",
    fileName: "dao-dong-dieu-hoa.pptx",
    fileExtension: "pptx",
    tier: "root",
    registryId: stamp("root", "Vật lý"),
    qualityLabel: "ministry_standard",
  },
  {
    id: "c3",
    title: "Đề kiểm tra giữa kỳ Hóa học 10",
    type: "learning_material",
    legacyType: "quiz",
    category: "learning_material",
    materialSubtype: "quiz",
    status: "pending",
    ownerId: "teacher",
    ownerName: "Lê Trung Hiếu",
    createdAt: "2026-06-02",
    views: 0,
    likes: 0,
    shares: 0,
    thumbnailColor: "#10B981",
    subject: "Hóa học",
    grade: "Lớp 10",
    platforms: ["national"],
    tags: ["Hóa", "Kiểm tra"],
    description: "Đề kiểm tra 45 phút giữa kỳ.",
    tier: "community",
    registryId: stamp("community", "Hóa học"),
    qualityLabel: "documented",
  },
  {
    id: "c4",
    title: "Sách Tiếng Anh 12 - Unit 3",
    type: "book",
    legacyType: "material",
    category: "book",
    materialType: "book",
    status: "published",
    ownerId: "publisher",
    ownerName: "Đỗ Văn Editor",
    createdAt: "2026-04-15",
    views: 12450,
    likes: 890,
    shares: 145,
    thumbnailColor: "#F59E0B",
    subject: "Tiếng Anh",
    grade: "Lớp 12",
    platforms: ["national", "ebooks"],
    tags: ["English", "Unit 3"],
    description: "Học liệu chính thống Unit 3 - Tiếng Anh 12.",
    tier: "partner",
    registryId: stamp("partner", "Tiếng Anh"),
    qualityLabel: "trusted_partner",
    license: { type: "commercial", scope: "national", rightsHolder: "NXB Giáo dục", validUntil: "2028-12-31", accessTerms: "paid" },
  },
  {
    id: "c5",
    title: "Nháp: Đề thi học kỳ Sinh học",
    type: "learning_material",
    legacyType: "quiz",
    category: "learning_material",
    materialSubtype: "quiz",
    status: "draft",
    ownerId: "teacher",
    ownerName: "Lê Trung Hiếu",
    createdAt: "2026-06-05",
    views: 0,
    likes: 0,
    shares: 0,
    thumbnailColor: "#EF4444",
    subject: "Sinh học",
    grade: "Lớp 9",
    platforms: [],
    tags: [],
    description: "",
    tier: "community",
    registryId: stamp("community", "Sinh học"),
    qualityLabel: "submitted",
  },
  {
    id: "c6",
    title: "Khóa học: Lịch sử Việt Nam thế kỷ XX",
    type: "course",
    legacyType: "material",
    category: "course",
    materialType: "course",
    status: "pending",
    ownerId: "teacher",
    ownerName: "Lê Trung Hiếu",
    createdAt: "2026-06-01",
    views: 0,
    likes: 0,
    shares: 0,
    thumbnailColor: "#8B5CF6",
    subject: "Lịch sử",
    grade: "Lớp 12",
    platforms: ["national"],
    tags: ["Lịch sử", "Việt Nam"],
    description: "Lộ trình học tổng quan Lịch sử VN.",
    tier: "community",
    registryId: stamp("community", "Lịch sử"),
    qualityLabel: "documented",
  },
  {
    id: "c7",
    title: "Đề luyện thi THPT QG - Toán",
    type: "learning_material",
    legacyType: "quiz",
    category: "learning_material",
    materialSubtype: "quiz",
    status: "rejected",
    ownerId: "teacher",
    ownerName: "Lê Trung Hiếu",
    createdAt: "2026-05-12",
    views: 0,
    likes: 0,
    shares: 0,
    thumbnailColor: "#717680",
    subject: "Toán",
    grade: "Lớp 12",
    platforms: ["national"],
    tags: ["THPT QG"],
    description: "Nội dung chưa đủ chuẩn — cần bổ sung lời giải.",
    tier: "community",
    registryId: stamp("community", "Toán"),
    qualityLabel: "rejected",
  },
  {
    id: "c8",
    title: "Atlas Địa lý Việt Nam tương tác",
    type: "learning_material",
    legacyType: "material",
    category: "learning_material",
    materialSubtype: "3d_vr",
    status: "published",
    ownerId: "publisher",
    ownerName: "Phạm Thu Manager",
    createdAt: "2026-03-20",
    views: 8920,
    likes: 654,
    shares: 89,
    thumbnailColor: "#10B981",
    subject: "Địa lý",
    grade: "Lớp 9",
    platforms: ["ebooks"],
    tags: ["Địa lý", "Atlas"],
    description: "Atlas tương tác bản đồ Việt Nam.",
    fileName: "atlas-vn.glb",
    fileExtension: "glb",
    tier: "partner",
    registryId: stamp("partner", "Địa lý"),
    qualityLabel: "trusted_partner",
    license: { type: "commercial", scope: "national", rightsHolder: "NXB Giáo dục", validUntil: "2028-12-31", accessTerms: "paid" },
  },
  {
    id: "c9",
    title: "Bộ đề Vật lý 11 - Chương Điện học",
    type: "learning_material",
    legacyType: "quiz",
    category: "learning_material",
    materialSubtype: "quiz",
    status: "draft",
    ownerId: "verified_teacher",
    ownerName: "Hoàng Xuân Nhi",
    createdAt: "2026-06-07",
    views: 0,
    likes: 0,
    shares: 0,
    thumbnailColor: "#2563EB",
    subject: "Vật lý",
    grade: "Lớp 11",
    platforms: [],
    tags: [],
    description: "",
  },
  {
    id: "c10",
    title: "Tài liệu: Văn học dân gian",
    type: "learning_material",
    legacyType: "material",
    category: "learning_material",
    materialSubtype: "document",
    status: "published",
    ownerId: "verified_teacher",
    ownerName: "Hoàng Xuân Nhi",
    createdAt: "2026-04-30",
    views: 3210,
    likes: 245,
    shares: 28,
    thumbnailColor: "#F59E0B",
    subject: "Ngữ văn",
    grade: "Lớp 10",
    platforms: ["national"],
    tags: ["Văn học", "Dân gian"],
    description: "Tổng hợp văn học dân gian Việt Nam.",
    fileName: "van-hoc-dan-gian.pdf",
    fileExtension: "pdf",
    tier: "root",
    registryId: stamp("root", "Ngữ văn"),
    qualityLabel: "ministry_standard",
  },
  {
    id: "c11",
    title: "Video bài giảng: Quang hợp ở thực vật",
    type: "learning_material",
    legacyType: "material",
    category: "learning_material",
    materialSubtype: "video",
    status: "published",
    ownerId: "verified_teacher",
    ownerName: "Hoàng Xuân Nhi",
    createdAt: "2026-05-02",
    views: 5640,
    likes: 421,
    shares: 67,
    thumbnailColor: "#10B981",
    subject: "Sinh học",
    grade: "Lớp 11",
    platforms: ["national", "ebooks"],
    tags: ["Sinh học", "Quang hợp"],
    description: "Video minh họa quá trình quang hợp.",
    fileName: "quang-hop.mp4",
    fileExtension: "mp4",
    tier: "root",
    registryId: stamp("root", "Sinh học"),
    qualityLabel: "ministry_standard",
  },
  {
    id: "c12",
    title: "Infographic: Bảng tuần hoàn hóa học",
    type: "learning_material",
    legacyType: "material",
    category: "learning_material",
    materialSubtype: "image",
    status: "published",
    ownerId: "publisher",
    ownerName: "Vũ Thị Biên Tập",
    createdAt: "2026-04-18",
    views: 7120,
    likes: 512,
    shares: 98,
    thumbnailColor: "#2563EB",
    subject: "Hóa học",
    grade: "Lớp 10",
    platforms: ["ebooks"],
    tags: ["Hóa học", "Infographic"],
    description: "Bảng tuần hoàn các nguyên tố trực quan.",
    fileName: "bang-tuan-hoan.png",
    fileExtension: "png",
    tier: "partner",
    registryId: stamp("partner", "Hóa học"),
    qualityLabel: "trusted_partner",
    license: { type: "commercial", scope: "national", rightsHolder: "NXB Giáo dục", validUntil: "2028-12-31", accessTerms: "paid" },
  },
  {
    id: "c13",
    title: "Audio luyện nghe Tiếng Anh 9",
    type: "learning_material",
    legacyType: "material",
    category: "learning_material",
    materialSubtype: "audio",
    status: "pending",
    ownerId: "publisher",
    ownerName: "Đỗ Văn Editor",
    createdAt: "2026-06-03",
    views: 0,
    likes: 0,
    shares: 0,
    thumbnailColor: "#F59E0B",
    subject: "Tiếng Anh",
    grade: "Lớp 9",
    platforms: ["national"],
    tags: ["English", "Listening"],
    description: "Bộ audio luyện kỹ năng nghe.",
    fileName: "listening-unit5.mp3",
    fileExtension: "mp3",
    tier: "partner",
    registryId: stamp("partner", "Tiếng Anh"),
    qualityLabel: "trusted_partner",
    license: { type: "commercial", scope: "national", rightsHolder: "NXB Giáo dục", validUntil: "2028-12-31", accessTerms: "paid" },
  },
  {
    id: "c14",
    title: "Gói SCORM: Mô phỏng mạch điện",
    type: "learning_material",
    legacyType: "material",
    category: "learning_material",
    materialSubtype: "scorm",
    status: "published",
    ownerId: "publisher",
    ownerName: "Phạm Thu Manager",
    createdAt: "2026-03-28",
    views: 2310,
    likes: 156,
    shares: 22,
    thumbnailColor: "#8B5CF6",
    subject: "Vật lý",
    grade: "Lớp 9",
    platforms: ["national", "ebooks"],
    tags: ["SCORM", "Mạch điện"],
    description: "Gói SCORM tích hợp LMS mô phỏng mạch điện.",
    fileName: "mach-dien-scorm.zip",
    fileExtension: "zip",
  },
  {
    id: "c15",
    title: "Học liệu nâng cao: Phòng thí nghiệm ảo Hóa",
    type: "learning_material",
    legacyType: "material",
    category: "learning_material",
    materialSubtype: "advanced",
    status: "published",
    ownerId: "publisher",
    ownerName: "Vũ Thị Biên Tập",
    createdAt: "2026-02-14",
    views: 4015,
    likes: 289,
    shares: 54,
    thumbnailColor: "#10B981",
    subject: "Hóa học",
    grade: "Lớp 11",
    platforms: ["ebooks"],
    tags: ["Lab ảo", "HTML5"],
    description: "Phòng thí nghiệm ảo tương tác HTML5.",
    fileName: "lab-hoa.zip",
    fileExtension: "html",
  },
  {
    id: "c16",
    title: "Sách bài tập Toán nâng cao 9",
    type: "book",
    legacyType: "material",
    category: "book",
    materialType: "book",
    status: "draft",
    ownerId: "publisher",
    ownerName: "Đỗ Văn Editor",
    createdAt: "2026-06-06",
    views: 0,
    likes: 0,
    shares: 0,
    thumbnailColor: "#20447E",
    subject: "Toán",
    grade: "Lớp 9",
    platforms: [],
    tags: ["Toán", "Nâng cao"],
    description: "",
  },
  {
    id: "c17",
    title: "Giáo trình Ngữ văn 11 — Tập 1",
    type: "book",
    legacyType: "material",
    category: "book",
    materialType: "book",
    status: "published",
    ownerId: "publisher",
    ownerName: "Phạm Thu Manager",
    createdAt: "2026-03-10",
    views: 18200,
    likes: 1340,
    shares: 210,
    thumbnailColor: "#8B5CF6",
    subject: "Ngữ văn",
    grade: "Lớp 11",
    platforms: ["national", "ebooks"],
    tags: ["Ngữ văn", "Giáo trình"],
    description: "Giáo trình chính thức Ngữ văn 11 — Tập 1.",
    tier: "partner",
    registryId: stamp("partner", "Ngữ văn"),
    qualityLabel: "trusted_partner",
    license: { type: "commercial", scope: "national", rightsHolder: "NXB Giáo dục", validUntil: "2028-12-31", accessTerms: "paid" },
  },
  {
    id: "c18",
    title: "Sách Toán 10 Cánh Diều",
    type: "book",
    legacyType: "material",
    category: "book",
    materialType: "book",
    status: "published",
    ownerId: "publisher",
    ownerName: "Lê Quốc Owner",
    createdAt: "2026-02-20",
    views: 22150,
    likes: 1780,
    shares: 320,
    thumbnailColor: "#2563EB",
    subject: "Toán",
    grade: "Lớp 10",
    platforms: ["national", "ebooks"],
    tags: ["Toán", "Cánh Diều"],
    description: "Sách giáo khoa Toán 10 bộ Cánh Diều.",
    tier: "partner",
    registryId: stamp("partner", "Toán"),
    qualityLabel: "trusted_partner",
    license: { type: "commercial", scope: "national", rightsHolder: "NXB Giáo dục", validUntil: "2028-12-31", accessTerms: "paid" },
  },
  {
    id: "c19",
    title: "Khóa học: Lập trình Python cơ bản",
    type: "course",
    legacyType: "material",
    category: "course",
    materialType: "course",
    status: "published",
    ownerId: "verified_teacher",
    ownerName: "Hoàng Xuân Nhi",
    createdAt: "2026-04-05",
    views: 9870,
    likes: 720,
    shares: 156,
    thumbnailColor: "#10B981",
    subject: "Tin học",
    grade: "Lớp 11",
    platforms: ["national", "ebooks"],
    tags: ["Python", "Lập trình"],
    description: "Khóa học lập trình Python từ cơ bản đến nâng cao.",
  },
  {
    id: "c20",
    title: "Khóa học: IELTS Writing Task 2",
    type: "course",
    legacyType: "material",
    category: "course",
    materialType: "course",
    status: "published",
    ownerId: "publisher",
    ownerName: "Đỗ Văn Editor",
    createdAt: "2026-05-08",
    views: 15340,
    likes: 1120,
    shares: 245,
    thumbnailColor: "#F59E0B",
    subject: "Tiếng Anh",
    grade: "Lớp 12",
    platforms: ["ebooks"],
    tags: ["IELTS", "Writing"],
    description: "Lộ trình chinh phục IELTS Writing Task 2.",
  },
  {
    id: "c21",
    title: "Bộ đề trắc nghiệm Sinh học 12",
    type: "learning_material",
    legacyType: "quiz",
    category: "learning_material",
    materialSubtype: "quiz",
    status: "published",
    ownerId: "verified_teacher",
    ownerName: "Hoàng Xuân Nhi",
    createdAt: "2026-05-15",
    views: 6540,
    likes: 489,
    shares: 78,
    thumbnailColor: "#10B981",
    subject: "Sinh học",
    grade: "Lớp 12",
    platforms: ["national"],
    tags: ["Sinh học", "Trắc nghiệm"],
    description: "200 câu trắc nghiệm ôn thi TN THPT.",
  },
  {
    id: "c22",
    title: "Video: Thí nghiệm Vật lý - Lực đàn hồi",
    type: "learning_material",
    legacyType: "material",
    category: "learning_material",
    materialSubtype: "video",
    status: "published",
    ownerId: "teacher",
    ownerName: "Lê Trung Hiếu",
    createdAt: "2026-05-22",
    views: 1820,
    likes: 134,
    shares: 19,
    thumbnailColor: "#EF4444",
    subject: "Vật lý",
    grade: "Lớp 10",
    platforms: ["national"],
    tags: ["Vật lý", "Thí nghiệm"],
    description: "Video thí nghiệm minh họa lực đàn hồi lò xo.",
    fileName: "luc-dan-hoi.mp4",
    fileExtension: "mp4",
    tier: "community",
    registryId: stamp("community", "Vật lý"),
    qualityLabel: "reviewed",
    coAuthors: ["Phạm Minh Tuấn"],
    versionHistory: [
      {
        version: "v1.2",
        date: "2026-05-22",
        note: "Bổ sung phụ đề và lồng tiếng phần phân tích kết quả thí nghiệm.",
        authorName: "Lê Trung Hiếu",
      },
      {
        version: "v1.1",
        date: "2026-05-10",
        note: "Quay lại cảnh đo độ giãn lò xo cho rõ thông số.",
        authorName: "Phạm Minh Tuấn",
      },
      {
        version: "v1.0",
        date: "2026-04-30",
        note: "Phiên bản đầu tiên đăng lên thư viện.",
        authorName: "Lê Trung Hiếu",
      },
    ],
  },
  {
    id: "c23",
    title: "Tài liệu: Công thức Hóa học THPT",
    type: "learning_material",
    legacyType: "material",
    category: "learning_material",
    materialSubtype: "document",
    status: "published",
    ownerId: "teacher",
    ownerName: "Lê Trung Hiếu",
    createdAt: "2026-04-28",
    views: 2450,
    likes: 178,
    shares: 32,
    thumbnailColor: "#10B981",
    subject: "Hóa học",
    grade: "Lớp 12",
    platforms: ["national"],
    tags: ["Hóa học", "Công thức"],
    description: "Tổng hợp toàn bộ công thức Hóa THPT.",
    fileName: "cong-thuc-hoa.pdf",
    fileExtension: "pdf",
    tier: "community",
    registryId: stamp("community", "Hóa học"),
    qualityLabel: "reviewed",
    coAuthors: ["Nguyễn Thị Lan", "Trần Văn Đức"],
    versionHistory: [
      {
        version: "v2.0",
        date: "2026-04-28",
        note: "Cập nhật theo chương trình GDPT 2018, thêm chuyên đề hóa hữu cơ.",
        authorName: "Lê Trung Hiếu",
      },
      {
        version: "v1.0",
        date: "2026-02-15",
        note: "Tổng hợp công thức Hóa học THPT lần đầu.",
        authorName: "Nguyễn Thị Lan",
      },
    ],
  },
  {
    id: "c24",
    title: "Bài giảng: Phép biến hình trong mặt phẳng",
    type: "learning_material",
    legacyType: "material",
    category: "learning_material",
    materialSubtype: "lesson",
    status: "published",
    ownerId: "verified_teacher",
    ownerName: "Hoàng Xuân Nhi",
    createdAt: "2026-04-12",
    views: 3680,
    likes: 267,
    shares: 45,
    thumbnailColor: "#8B5CF6",
    subject: "Toán",
    grade: "Lớp 11",
    platforms: ["national", "ebooks"],
    tags: ["Toán", "Hình học"],
    description: "Bài giảng chi tiết về phép tịnh tiến, đối xứng, quay.",
    fileName: "phep-bien-hinh.pptx",
    fileExtension: "pptx",
  },
  {
    id: "c25",
    title: "Đề kiểm tra 15 phút - Toán 8",
    type: "learning_material",
    legacyType: "quiz",
    category: "learning_material",
    materialSubtype: "quiz",
    status: "published",
    ownerId: "teacher",
    ownerName: "Lê Trung Hiếu",
    createdAt: "2026-05-30",
    views: 890,
    likes: 45,
    shares: 8,
    thumbnailColor: "#F59E0B",
    subject: "Toán",
    grade: "Lớp 8",
    platforms: ["national"],
    tags: ["Toán", "Kiểm tra"],
    description: "Đề kiểm tra nhanh 15 phút chương Hình học.",
  },
  {
    id: "c26",
    title: "Hình ảnh: Sơ đồ tư duy Lịch sử VN",
    type: "learning_material",
    legacyType: "material",
    category: "learning_material",
    materialSubtype: "image",
    status: "published",
    ownerId: "teacher",
    ownerName: "Lê Trung Hiếu",
    createdAt: "2026-05-18",
    views: 1560,
    likes: 112,
    shares: 24,
    thumbnailColor: "#8B5CF6",
    subject: "Lịch sử",
    grade: "Lớp 12",
    platforms: ["national"],
    tags: ["Lịch sử", "Sơ đồ tư duy"],
    description: "Sơ đồ tóm tắt các giai đoạn lịch sử VN.",
    fileName: "so-do-tu-duy-ls.png",
    fileExtension: "png",
  },
  {
    id: "c27",
    title: "Khóa ôn thi TN THPT Toán 2026",
    type: "course",
    legacyType: "material",
    category: "course",
    materialType: "course",
    status: "draft",
    ownerId: "verified_teacher",
    ownerName: "Hoàng Xuân Nhi",
    createdAt: "2026-06-08",
    views: 0,
    likes: 0,
    shares: 0,
    thumbnailColor: "#2563EB",
    subject: "Toán",
    grade: "Lớp 12",
    platforms: [],
    tags: ["Toán", "THPT QG"],
    description: "",
  },
  {
    id: "c28",
    title: "Sách Khoa học tự nhiên 6",
    type: "book",
    legacyType: "material",
    category: "book",
    materialType: "book",
    status: "published",
    ownerId: "publisher",
    ownerName: "Vũ Thị Biên Tập",
    createdAt: "2026-01-15",
    views: 14780,
    likes: 1050,
    shares: 178,
    thumbnailColor: "#10B981",
    subject: "KHTN",
    grade: "Lớp 6",
    platforms: ["national", "ebooks"],
    tags: ["KHTN", "Lớp 6"],
    description: "Sách giáo khoa Khoa học tự nhiên 6.",
  },
];

/* ─── Nội dung riêng theo từng kênh/tổ chức (cảm giác website thật) ──────
 * Mỗi node có bộ học liệu khác biệt. ownerId giữ giá trị RoleId hợp lệ (fallback
 * luồng cũ); ownerNodeId là chủ sở hữu thật theo cây tổ chức (luồng identity).
 * ──────────────────────────────────────────────────────────────────────── */
const NODE_SEED_CONTENT: ContentItem[] = [
  // ── Chi nhánh Toán (nxbgd-toan) ───────────────────────────────────────
  { id: "n1", title: "SGK Toán 10 — Tập 1 (bản điện tử)", type: "book", category: "book", status: "published", ownerId: "publisher", ownerNodeId: "nxbgd-toan", ownerName: "Chi nhánh Toán", createdAt: "2026-01-12", views: 18420, likes: 1240, shares: 318, thumbnailColor: "#237BD3", subject: "Toán", grade: "Lớp 10", platforms: ["national", "ebooks"], tags: ["SGK", "Toán", "Lớp 10"], description: "Sách giáo khoa Toán 10 tập 1 theo chương trình GDPT 2018.", tier: "root", registryId: stamp("root", "Toán"), qualityLabel: "ministry_standard" },
  { id: "n2", title: "Chuyên đề Hàm số bậc hai", type: "course", category: "course", status: "published", ownerId: "publisher", ownerNodeId: "nxbgd-toan", ownerName: "Chi nhánh Toán", createdAt: "2026-02-03", views: 7330, likes: 540, shares: 96, thumbnailColor: "#20447E", subject: "Toán", grade: "Lớp 10", platforms: ["national"], tags: ["Hàm số", "Chuyên đề"], description: "Khóa học chuyên sâu về hàm số bậc hai và đồ thị.", tier: "root", registryId: stamp("root", "Toán"), qualityLabel: "reviewed" },
  { id: "n3", title: "1000 bài tập Hình học không gian 11", type: "learning_material", legacyType: "material", category: "learning_material", materialSubtype: "document", status: "published", ownerId: "publisher", ownerNodeId: "nxbgd-toan", ownerName: "Chi nhánh Toán", createdAt: "2026-02-21", views: 9610, likes: 712, shares: 130, thumbnailColor: "#0EA5A4", subject: "Toán", grade: "Lớp 11", platforms: ["national", "ebooks"], tags: ["Hình học", "Bài tập"], description: "Tuyển tập 1000 bài tập hình học không gian có lời giải.", fileName: "hinh-hoc-kg-11.pdf", fileExtension: "pdf", tier: "root", registryId: stamp("root", "Toán"), qualityLabel: "ministry_standard" },
  { id: "n4", title: "Đề kiểm tra giữa kỳ Toán 11", type: "learning_material", legacyType: "quiz", category: "learning_material", materialSubtype: "quiz", status: "published", ownerId: "publisher", ownerNodeId: "nxbgd-toan", ownerName: "Chi nhánh Toán", createdAt: "2026-03-09", views: 5120, likes: 388, shares: 64, thumbnailColor: "#237BD3", subject: "Toán", grade: "Lớp 11", platforms: ["national"], tags: ["Đề thi", "Giữa kỳ"], description: "Bộ đề kiểm tra giữa học kỳ môn Toán lớp 11.", tier: "root", registryId: stamp("root", "Toán"), qualityLabel: "reviewed" },
  { id: "n5", title: "Bài giảng Lượng giác — Lớp 11", type: "learning_material", legacyType: "material", category: "learning_material", materialSubtype: "video", status: "pending", ownerId: "publisher", ownerNodeId: "nxbgd-toan", ownerName: "Chi nhánh Toán", createdAt: "2026-06-02", views: 0, likes: 0, shares: 0, thumbnailColor: "#7C3AED", subject: "Toán", grade: "Lớp 11", platforms: ["national"], tags: ["Lượng giác", "Video"], description: "Bài giảng video về công thức lượng giác.", qualityLabel: "documented" },

  // ── Chi nhánh Ngữ văn (nxbgd-van) ─────────────────────────────────────
  { id: "n6", title: "SGK Ngữ văn 10 — Kết nối tri thức", type: "book", category: "book", status: "published", ownerId: "publisher", ownerNodeId: "nxbgd-van", ownerName: "Chi nhánh Ngữ văn", createdAt: "2026-01-15", views: 15880, likes: 1080, shares: 270, thumbnailColor: "#0EA5A4", subject: "Ngữ văn", grade: "Lớp 10", platforms: ["national", "ebooks"], tags: ["SGK", "Ngữ văn"], description: "Sách giáo khoa Ngữ văn 10 bộ Kết nối tri thức.", tier: "root", registryId: stamp("root", "Ngữ văn"), qualityLabel: "ministry_standard" },
  { id: "n7", title: "Đọc hiểu văn bản nghị luận", type: "course", category: "course", status: "published", ownerId: "publisher", ownerNodeId: "nxbgd-van", ownerName: "Chi nhánh Ngữ văn", createdAt: "2026-02-18", views: 6240, likes: 452, shares: 71, thumbnailColor: "#16A34A", subject: "Ngữ văn", grade: "Lớp 12", platforms: ["national"], tags: ["Đọc hiểu", "Nghị luận"], description: "Khóa học kỹ năng đọc hiểu văn bản nghị luận.", tier: "root", registryId: stamp("root", "Ngữ văn"), qualityLabel: "reviewed" },
  { id: "n8", title: "Tuyển tập đề thi Ngữ văn THPT", type: "learning_material", legacyType: "material", category: "learning_material", materialSubtype: "document", status: "published", ownerId: "publisher", ownerNodeId: "nxbgd-van", ownerName: "Chi nhánh Ngữ văn", createdAt: "2026-03-22", views: 8120, likes: 590, shares: 118, thumbnailColor: "#0EA5A4", subject: "Ngữ văn", grade: "Lớp 12", platforms: ["national", "ebooks"], tags: ["Đề thi", "THPT"], description: "Tuyển tập đề thi tham khảo môn Ngữ văn.", fileName: "de-thi-van-thpt.pdf", fileExtension: "pdf", tier: "root", registryId: stamp("root", "Ngữ văn"), qualityLabel: "ministry_standard" },
  { id: "n9", title: "Bài giảng: Truyện Kiều — Nguyễn Du", type: "learning_material", legacyType: "material", category: "learning_material", materialSubtype: "lesson", status: "published", ownerId: "publisher", ownerNodeId: "nxbgd-van", ownerName: "Chi nhánh Ngữ văn", createdAt: "2026-04-05", views: 4960, likes: 401, shares: 58, thumbnailColor: "#E11D48", subject: "Ngữ văn", grade: "Lớp 11", platforms: ["national"], tags: ["Truyện Kiều", "Văn học"], description: "Bài giảng phân tích tác phẩm Truyện Kiều.", tier: "root", registryId: stamp("root", "Ngữ văn"), qualityLabel: "reviewed" },
  { id: "n10", title: "Sổ tay nghị luận xã hội", type: "learning_material", legacyType: "material", category: "learning_material", materialSubtype: "document", status: "pending", ownerId: "publisher", ownerNodeId: "nxbgd-van", ownerName: "Chi nhánh Ngữ văn", createdAt: "2026-06-10", views: 0, likes: 0, shares: 0, thumbnailColor: "#EA580C", subject: "Ngữ văn", grade: "Lớp 12", platforms: ["national"], tags: ["Làm văn", "NLXH"], description: "Sổ tay hướng dẫn viết nghị luận xã hội.", qualityLabel: "documented" },

  // ── VietEdu — EdTech tương tác (vietedu) ──────────────────────────────
  { id: "n11", title: "Lớp học thích ứng: Toán 6 (AI)", type: "course", category: "course", status: "published", ownerId: "publisher", ownerNodeId: "vietedu", ownerName: "VietEdu", createdAt: "2026-02-08", views: 21300, likes: 1820, shares: 460, thumbnailColor: "#7C3AED", subject: "Toán", grade: "Lớp 6", platforms: ["national"], tags: ["Adaptive", "AI", "Toán"], description: "Lộ trình học thích ứng cá nhân hóa theo năng lực bằng AI.", tier: "partner", registryId: stamp("partner", "Toán"), qualityLabel: "trusted_partner", license: { type: "commercial", scope: "national", rightsHolder: "Công ty VietEdu", validUntil: "2028-12-31", accessTerms: "paid" } },
  { id: "n12", title: "Phòng thí nghiệm ảo Hóa học 3D", type: "learning_material", legacyType: "material", category: "learning_material", materialSubtype: "3d_vr", status: "published", ownerId: "publisher", ownerNodeId: "vietedu", ownerName: "VietEdu", createdAt: "2026-03-01", views: 16740, likes: 1510, shares: 392, thumbnailColor: "#237BD3", subject: "Hóa học", grade: "Lớp 10", platforms: ["national"], tags: ["3D", "VR", "Thí nghiệm"], description: "Mô phỏng thí nghiệm hóa học an toàn trong không gian 3D.", tier: "partner", registryId: stamp("partner", "Hóa học"), qualityLabel: "trusted_partner", license: { type: "commercial", scope: "national", rightsHolder: "Công ty VietEdu", validUntil: "2028-12-31", accessTerms: "paid" } },
  { id: "n13", title: "Tiếng Anh giao tiếp — Video tương tác", type: "course", category: "course", status: "published", ownerId: "publisher", ownerNodeId: "vietedu", ownerName: "VietEdu", createdAt: "2026-03-19", views: 13920, likes: 1190, shares: 305, thumbnailColor: "#0EA5A4", subject: "Tiếng Anh", grade: "Lớp 9", platforms: ["national"], tags: ["Tiếng Anh", "Tương tác"], description: "Khóa video luyện phản xạ giao tiếp có chấm điểm phát âm.", tier: "partner", registryId: stamp("partner", "Tiếng Anh"), qualityLabel: "trusted_partner", license: { type: "commercial", scope: "national", rightsHolder: "Công ty VietEdu", validUntil: "2027-12-31", accessTerms: "paid" } },
  { id: "n14", title: "Bộ đề luyện thi thích ứng IELTS", type: "learning_material", legacyType: "quiz", category: "learning_material", materialSubtype: "quiz", status: "published", ownerId: "publisher", ownerNodeId: "vietedu", ownerName: "VietEdu", createdAt: "2026-04-12", views: 9870, likes: 860, shares: 214, thumbnailColor: "#7C3AED", subject: "Tiếng Anh", grade: "Lớp 12", platforms: ["national"], tags: ["IELTS", "Adaptive"], description: "Ngân hàng đề luyện thi IELTS điều chỉnh độ khó theo lực học.", tier: "partner", qualityLabel: "trusted_partner" },
  { id: "n15", title: "Mô phỏng Vật lý: Điện từ trường (VR)", type: "learning_material", legacyType: "material", category: "learning_material", materialSubtype: "3d_vr", status: "published", ownerId: "publisher", ownerNodeId: "vietedu", ownerName: "VietEdu", createdAt: "2026-04-28", views: 8450, likes: 770, shares: 188, thumbnailColor: "#2563EB", subject: "Vật lý", grade: "Lớp 11", platforms: ["national"], tags: ["VR", "Vật lý"], description: "Mô phỏng trực quan điện trường, từ trường trong VR.", tier: "partner", qualityLabel: "trusted_partner" },
  { id: "n16", title: "Game hóa: Học bảng tuần hoàn", type: "learning_material", legacyType: "material", category: "learning_material", materialSubtype: "advanced", status: "published", ownerId: "publisher", ownerNodeId: "vietedu", ownerName: "VietEdu", createdAt: "2026-05-15", views: 11260, likes: 1030, shares: 277, thumbnailColor: "#16A34A", subject: "Hóa học", grade: "Lớp 10", platforms: ["national"], tags: ["Game hóa", "Tương tác"], description: "Học liệu game hóa giúp ghi nhớ bảng tuần hoàn nguyên tố.", tier: "partner", qualityLabel: "trusted_partner" },

  // ── Nguyễn Minh Hồng — cá nhân, Tiếng Anh (pn-hong) ───────────────────
  { id: "n17", title: "Phonics cho học sinh tiểu học", type: "learning_material", legacyType: "material", category: "learning_material", materialSubtype: "lesson", status: "published", ownerId: "teacher", ownerNodeId: "pn-hong", ownerName: "Nguyễn Minh Hồng", createdAt: "2026-03-02", views: 3210, likes: 268, shares: 47, thumbnailColor: "#F59E0B", subject: "Tiếng Anh", grade: "Lớp 3", platforms: ["national"], tags: ["Phonics", "Tiểu học"], description: "Bộ bài giảng phát âm Phonics cho học sinh tiểu học.", tier: "community", qualityLabel: "reviewed" },
  { id: "n18", title: "100 flashcard từ vựng THCS", type: "learning_material", legacyType: "material", category: "learning_material", materialSubtype: "document", status: "published", ownerId: "teacher", ownerNodeId: "pn-hong", ownerName: "Nguyễn Minh Hồng", createdAt: "2026-04-09", views: 2540, likes: 201, shares: 39, thumbnailColor: "#EA580C", subject: "Tiếng Anh", grade: "Lớp 7", platforms: ["national"], tags: ["Từ vựng", "Flashcard"], description: "Bộ 100 flashcard từ vựng theo chủ đề cho học sinh THCS.", tier: "community", qualityLabel: "reviewed" },
  { id: "n19", title: "Bài tập ngữ pháp Tiếng Anh 7", type: "learning_material", legacyType: "quiz", category: "learning_material", materialSubtype: "quiz", status: "draft", ownerId: "teacher", ownerNodeId: "pn-hong", ownerName: "Nguyễn Minh Hồng", createdAt: "2026-06-14", views: 0, likes: 0, shares: 0, thumbnailColor: "#237BD3", subject: "Tiếng Anh", grade: "Lớp 7", platforms: ["national"], tags: ["Ngữ pháp", "Bài tập"], description: "Bộ bài tập ngữ pháp theo từng đơn vị bài học (đang soạn).", tier: "community", qualityLabel: "submitted" },

  // ── Lê Trung Hiếu — cá nhân, Hóa học THCS (pn-hieu) ───────────────────
  { id: "n20", title: "Thí nghiệm điện phân — video hướng dẫn", type: "learning_material", legacyType: "material", category: "learning_material", materialSubtype: "video", status: "published", ownerId: "teacher", ownerNodeId: "pn-hieu", ownerName: "Lê Trung Hiếu", createdAt: "2026-03-11", views: 1820, likes: 156, shares: 28, thumbnailColor: "#16A34A", subject: "Hóa học", grade: "Lớp 9", platforms: ["national"], tags: ["Thí nghiệm", "Điện phân"], description: "Video hướng dẫn thí nghiệm điện phân dung dịch.", tier: "community", qualityLabel: "reviewed" },
  { id: "n21", title: "Bộ đề Hóa học 9 — Học kỳ 1", type: "learning_material", legacyType: "quiz", category: "learning_material", materialSubtype: "quiz", status: "published", ownerId: "teacher", ownerNodeId: "pn-hieu", ownerName: "Lê Trung Hiếu", createdAt: "2026-04-20", views: 2110, likes: 174, shares: 31, thumbnailColor: "#7C3AED", subject: "Hóa học", grade: "Lớp 9", platforms: ["national"], tags: ["Đề thi", "Học kỳ 1"], description: "Bộ đề ôn tập Hóa học 9 học kỳ 1 có đáp án.", tier: "community", qualityLabel: "reviewed" },
  { id: "n22", title: "Bài giảng: Bảng tuần hoàn nguyên tố", type: "learning_material", legacyType: "material", category: "learning_material", materialSubtype: "lesson", status: "published", ownerId: "teacher", ownerNodeId: "pn-hieu", ownerName: "Lê Trung Hiếu", createdAt: "2026-05-06", views: 1640, likes: 143, shares: 22, thumbnailColor: "#2563EB", subject: "Hóa học", grade: "Lớp 8", platforms: ["national"], tags: ["Bảng tuần hoàn"], description: "Bài giảng giới thiệu cấu trúc bảng tuần hoàn nguyên tố.", tier: "community", qualityLabel: "documented" },

  // ── Hoàng Xuân Nhi — cá nhân, Toán THPT chuyên (pn-nhi) ───────────────
  { id: "n23", title: "Bồi dưỡng HSG: Chuyên đề Số học", type: "course", category: "course", status: "published", ownerId: "verified_teacher", ownerNodeId: "pn-nhi", ownerName: "Hoàng Xuân Nhi", createdAt: "2026-02-26", views: 5680, likes: 487, shares: 92, thumbnailColor: "#2563EB", subject: "Toán", grade: "Lớp 12", platforms: ["national"], tags: ["HSG", "Số học"], description: "Khóa bồi dưỡng học sinh giỏi chuyên đề số học.", tier: "community", qualityLabel: "reviewed" },
  { id: "n24", title: "Tuyển tập đề thi chuyên Toán", type: "learning_material", legacyType: "material", category: "learning_material", materialSubtype: "document", status: "published", ownerId: "verified_teacher", ownerNodeId: "pn-nhi", ownerName: "Hoàng Xuân Nhi", createdAt: "2026-04-02", views: 4920, likes: 420, shares: 80, thumbnailColor: "#20447E", subject: "Toán", grade: "Lớp 12", platforms: ["national", "ebooks"], tags: ["Đề thi", "Chuyên Toán"], description: "Tuyển tập đề thi vào lớp chuyên Toán các năm.", fileName: "de-chuyen-toan.pdf", fileExtension: "pdf", tier: "community", qualityLabel: "reviewed" },

  // ── NXB Giáo dục VN — gốc, liên môn (nxbgd) ───────────────────────────
  { id: "n25", title: "Bộ SGK lớp 12 (trọn bộ)", type: "book", category: "book", status: "published", ownerId: "publisher", ownerNodeId: "nxbgd", ownerName: "NXB Giáo dục VN", createdAt: "2026-01-20", views: 31250, likes: 2410, shares: 640, thumbnailColor: "#20447E", subject: "Toán", grade: "Lớp 12", platforms: ["national", "ebooks"], tags: ["SGK", "Trọn bộ"], description: "Bộ sách giáo khoa lớp 12 đầy đủ các môn, bản điện tử.", tier: "root", registryId: stamp("root", "Toán"), qualityLabel: "ministry_standard" },
  { id: "n26", title: "Tài liệu hướng dẫn dạy học GDPT 2018", type: "learning_material", legacyType: "material", category: "learning_material", materialSubtype: "document", status: "published", ownerId: "publisher", ownerNodeId: "nxbgd", ownerName: "NXB Giáo dục VN", createdAt: "2026-02-14", views: 14300, likes: 980, shares: 410, thumbnailColor: "#0EA5A4", subject: "Ngữ văn", grade: "Lớp 10", platforms: ["national"], tags: ["GDPT 2018", "Hướng dẫn"], description: "Tài liệu hướng dẫn triển khai chương trình GDPT 2018 cho giáo viên.", tier: "root", registryId: stamp("root", "Ngữ văn"), qualityLabel: "ministry_standard" },
];

/* Gán ownerNodeId cho các item cũ (theo ownerId) để scope theo node hoạt động,
 * rồi gộp nội dung riêng từng kênh vào SEED_CONTENT. */
const OWNER_NODE_BY_ROLE: Partial<Record<RoleId, string>> = {
  publisher: "nxbgd",
  teacher: "pn-hieu",
  verified_teacher: "pn-nhi",
};
for (const item of SEED_CONTENT) {
  if (!item.ownerNodeId) item.ownerNodeId = OWNER_NODE_BY_ROLE[item.ownerId];
}
SEED_CONTENT.push(...NODE_SEED_CONTENT);

export const VERIFICATION_REQUESTS: VerificationRequest[] = [
  {
    id: "vr1",
    applicantId: "teacher",
    accountType: "Cá nhân",
    status: "pending",
    submittedAt: "2026-06-08",
    documents: ["chung-chi-su-pham.pdf", "the-giao-vien.jpg"],
    materialsCount: 5,
    views: 620,
    accountAgeDays: 210,
  },
  {
    id: "vr2",
    applicantId: "publisher",
    accountType: "Doanh nghiệp",
    status: "pending",
    submittedAt: "2026-06-09",
    documents: ["giay-phep-xuat-ban.pdf", "quyet-dinh-thanh-lap.pdf"],
    materialsCount: 12,
    views: 64810,
    accountAgeDays: 285,
  },
];

export const CONTENT_REPORTS: ContentReport[] = [
  {
    id: "rp1",
    contentId: "c7",
    contentTitle: "Đề luyện thi THPT QG - Toán",
    reason: "inaccurate",
    reporterName: "Phụ huynh Lớp 12A",
    reportedAt: "2026-06-07",
    status: "open",
    note: "Đáp án câu 14 chưa chính xác.",
  },
  {
    id: "rp2",
    contentId: "c12",
    contentTitle: "Infographic: Bảng tuần hoàn hóa học",
    reason: "copyright",
    reporterName: "NXB Khác",
    reportedAt: "2026-06-05",
    status: "open",
    note: "Nghi ngờ vi phạm bản quyền hình ảnh.",
  },
  {
    id: "rp3",
    contentId: "c11",
    contentTitle: "Video bài giảng: Quang hợp ở thực vật",
    reason: "spam",
    reporterName: "Giáo viên ẩn danh",
    reportedAt: "2026-06-02",
    status: "open",
  },
];

export const SAMPLE_QUESTIONS: Question[] = [
  {
    id: "q1",
    type: "multiple_choice",
    prompt: "Phương trình nào sau đây là phương trình bậc nhất một ẩn?",
    options: [
      { id: "a", text: "2x + 3 = 0" },
      { id: "b", text: "x² - 4 = 0" },
      { id: "c", text: "x³ + x = 1" },
      { id: "d", text: "2x + y = 5" },
    ],
    correctOptionId: "a",
    duration: 30,
    points: 1,
    required: true,
  },
  {
    id: "q2",
    type: "drag_drop",
    prompt: "Ghép cặp đại lượng vật lý với đơn vị đo:",
    pairs: [
      { id: "p1", left: "Lực", right: "Newton (N)" },
      { id: "p2", left: "Năng lượng", right: "Joule (J)" },
      { id: "p3", left: "Công suất", right: "Watt (W)" },
    ],
    duration: 60,
    points: 2,
    required: true,
  },
  {
    id: "q3",
    type: "essay",
    prompt: "Trình bày định luật bảo toàn năng lượng và cho một ví dụ minh họa.",
    essayAnswer: "",
    duration: 300,
    points: 5,
    required: false,
  },
];

export const ANALYTICS_30D = Array.from({ length: 30 }, (_, i) => ({
  date: `Ngày ${i + 1}`,
  views: Math.round(200 + Math.sin(i / 3) * 80 + ((i * 53) % 120)),
}));

export const ANALYTICS_7D = ANALYTICS_30D.slice(-7);
export const ANALYTICS_90D = Array.from({ length: 90 }, (_, i) => ({
  date: `N${i + 1}`,
  views: Math.round(180 + Math.sin(i / 5) * 100 + ((i * 37) % 150)),
}));
