/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentRouteImport } from './routes/student'
import { Route as SchoolRouteImport } from './routes/school'
import { Route as ReviewerRouteImport } from './routes/reviewer'
import { Route as OrgRouteImport } from './routes/org'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CreatorRouteImport } from './routes/creator'
import { Route as ChooseProfileRouteImport } from './routes/choose-profile'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentProgressRouteImport } from './routes/student.progress'
import { Route as StudentHomeRouteImport } from './routes/student.home'
import { Route as StudentExploreRouteImport } from './routes/student.explore'
import { Route as SchoolReviewRouteImport } from './routes/school.review'
import { Route as SchoolDashboardRouteImport } from './routes/school.dashboard'
import { Route as ReviewerReportsRouteImport } from './routes/reviewer.reports'
import { Route as ReviewerQueueRouteImport } from './routes/reviewer.queue'
import { Route as OrgVerificationRouteImport } from './routes/org.verification'
import { Route as OrgStudioRouteImport } from './routes/org.studio'
import { Route as OrgStructureRouteImport } from './routes/org.structure'
import { Route as OrgSigningRouteImport } from './routes/org.signing'
import { Route as OrgSettingsRouteImport } from './routes/org.settings'
import { Route as OrgMembersRouteImport } from './routes/org.members'
import { Route as OrgLibraryRouteImport } from './routes/org.library'
import { Route as OrgDashboardRouteImport } from './routes/org.dashboard'
import { Route as OrgChannelRouteImport } from './routes/org.channel'
import { Route as OrgAnalyticsRouteImport } from './routes/org.analytics'
import { Route as CreatorVerificationRouteImport } from './routes/creator.verification'
import { Route as CreatorStudioRouteImport } from './routes/creator.studio'
import { Route as CreatorSettingsRouteImport } from './routes/creator.settings'
import { Route as CreatorRegistryRouteImport } from './routes/creator.registry'
import { Route as CreatorLibraryRouteImport } from './routes/creator.library'
import { Route as CreatorDeptReviewRouteImport } from './routes/creator.dept-review'
import { Route as CreatorDashboardRouteImport } from './routes/creator.dashboard'
import { Route as CreatorChannelRouteImport } from './routes/creator.channel'
import { Route as AdminVerificationRequestsRouteImport } from './routes/admin.verification-requests'
import { Route as AdminVerificationRouteImport } from './routes/admin.verification'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminStudioRouteImport } from './routes/admin.studio'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminLibraryRouteImport } from './routes/admin.library'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminContentReviewRouteImport } from './routes/admin.content-review'
import { Route as AdminChannelRouteImport } from './routes/admin.channel'
import { Route as StudentLearnIdRouteImport } from './routes/student.learn.$id'
import { Route as ReviewerReviewIdRouteImport } from './routes/reviewer.review.$id'
import { Route as OrgStudioNewRouteImport } from './routes/org.studio.new'
import { Route as OrgChannelEditRouteImport } from './routes/org.channel.edit'
import { Route as CreatorStudioNewRouteImport } from './routes/creator.studio.new'
import { Route as CreatorChannelEditRouteImport } from './routes/creator.channel.edit'
import { Route as OrgBuilderQuizIdRouteImport } from './routes/org.builder.quiz.$id'
import { Route as OrgBuilderMaterialIdRouteImport } from './routes/org.builder.material.$id'
import { Route as OrgBuilderCourseIdRouteImport } from './routes/org.builder.course.$id'
import { Route as OrgBuilderBookIdRouteImport } from './routes/org.builder.book.$id'
import { Route as CreatorBuilderQuizIdRouteImport } from './routes/creator.builder.quiz.$id'
import { Route as CreatorBuilderMaterialIdRouteImport } from './routes/creator.builder.material.$id'
import { Route as CreatorBuilderCourseIdRouteImport } from './routes/creator.builder.course.$id'
import { Route as CreatorBuilderBookIdRouteImport } from './routes/creator.builder.book.$id'

const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolRoute = SchoolRouteImport.update({
  id: '/school',
  path: '/school',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewerRoute = ReviewerRouteImport.update({
  id: '/reviewer',
  path: '/reviewer',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgRoute = OrgRouteImport.update({
  id: '/org',
  path: '/org',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorRoute = CreatorRouteImport.update({
  id: '/creator',
  path: '/creator',
  getParentRoute: () => rootRouteImport,
} as any)
const ChooseProfileRoute = ChooseProfileRouteImport.update({
  id: '/choose-profile',
  path: '/choose-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentProgressRoute = StudentProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => StudentRoute,
} as any)
const StudentHomeRoute = StudentHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => StudentRoute,
} as any)
const StudentExploreRoute = StudentExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => StudentRoute,
} as any)
const SchoolReviewRoute = SchoolReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => SchoolRoute,
} as any)
const SchoolDashboardRoute = SchoolDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => SchoolRoute,
} as any)
const ReviewerReportsRoute = ReviewerReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => ReviewerRoute,
} as any)
const ReviewerQueueRoute = ReviewerQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => ReviewerRoute,
} as any)
const OrgVerificationRoute = OrgVerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => OrgRoute,
} as any)
const OrgStudioRoute = OrgStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => OrgRoute,
} as any)
const OrgStructureRoute = OrgStructureRouteImport.update({
  id: '/structure',
  path: '/structure',
  getParentRoute: () => OrgRoute,
} as any)
const OrgSigningRoute = OrgSigningRouteImport.update({
  id: '/signing',
  path: '/signing',
  getParentRoute: () => OrgRoute,
} as any)
const OrgSettingsRoute = OrgSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => OrgRoute,
} as any)
const OrgMembersRoute = OrgMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => OrgRoute,
} as any)
const OrgLibraryRoute = OrgLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => OrgRoute,
} as any)
const OrgDashboardRoute = OrgDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => OrgRoute,
} as any)
const OrgChannelRoute = OrgChannelRouteImport.update({
  id: '/channel',
  path: '/channel',
  getParentRoute: () => OrgRoute,
} as any)
const OrgAnalyticsRoute = OrgAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => OrgRoute,
} as any)
const CreatorVerificationRoute = CreatorVerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => CreatorRoute,
} as any)
const CreatorStudioRoute = CreatorStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => CreatorRoute,
} as any)
const CreatorSettingsRoute = CreatorSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => CreatorRoute,
} as any)
const CreatorRegistryRoute = CreatorRegistryRouteImport.update({
  id: '/registry',
  path: '/registry',
  getParentRoute: () => CreatorRoute,
} as any)
const CreatorLibraryRoute = CreatorLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => CreatorRoute,
} as any)
const CreatorDeptReviewRoute = CreatorDeptReviewRouteImport.update({
  id: '/dept-review',
  path: '/dept-review',
  getParentRoute: () => CreatorRoute,
} as any)
const CreatorDashboardRoute = CreatorDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => CreatorRoute,
} as any)
const CreatorChannelRoute = CreatorChannelRouteImport.update({
  id: '/channel',
  path: '/channel',
  getParentRoute: () => CreatorRoute,
} as any)
const AdminVerificationRequestsRoute =
  AdminVerificationRequestsRouteImport.update({
    id: '/verification-requests',
    path: '/verification-requests',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminVerificationRoute = AdminVerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudioRoute = AdminStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLibraryRoute = AdminLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentReviewRoute = AdminContentReviewRouteImport.update({
  id: '/content-review',
  path: '/content-review',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChannelRoute = AdminChannelRouteImport.update({
  id: '/channel',
  path: '/channel',
  getParentRoute: () => AdminRoute,
} as any)
const StudentLearnIdRoute = StudentLearnIdRouteImport.update({
  id: '/learn/$id',
  path: '/learn/$id',
  getParentRoute: () => StudentRoute,
} as any)
const ReviewerReviewIdRoute = ReviewerReviewIdRouteImport.update({
  id: '/review/$id',
  path: '/review/$id',
  getParentRoute: () => ReviewerRoute,
} as any)
const OrgStudioNewRoute = OrgStudioNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => OrgStudioRoute,
} as any)
const OrgChannelEditRoute = OrgChannelEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => OrgChannelRoute,
} as any)
const CreatorStudioNewRoute = CreatorStudioNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => CreatorStudioRoute,
} as any)
const CreatorChannelEditRoute = CreatorChannelEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => CreatorChannelRoute,
} as any)
const OrgBuilderQuizIdRoute = OrgBuilderQuizIdRouteImport.update({
  id: '/builder/quiz/$id',
  path: '/builder/quiz/$id',
  getParentRoute: () => OrgRoute,
} as any)
const OrgBuilderMaterialIdRoute = OrgBuilderMaterialIdRouteImport.update({
  id: '/builder/material/$id',
  path: '/builder/material/$id',
  getParentRoute: () => OrgRoute,
} as any)
const OrgBuilderCourseIdRoute = OrgBuilderCourseIdRouteImport.update({
  id: '/builder/course/$id',
  path: '/builder/course/$id',
  getParentRoute: () => OrgRoute,
} as any)
const OrgBuilderBookIdRoute = OrgBuilderBookIdRouteImport.update({
  id: '/builder/book/$id',
  path: '/builder/book/$id',
  getParentRoute: () => OrgRoute,
} as any)
const CreatorBuilderQuizIdRoute = CreatorBuilderQuizIdRouteImport.update({
  id: '/builder/quiz/$id',
  path: '/builder/quiz/$id',
  getParentRoute: () => CreatorRoute,
} as any)
const CreatorBuilderMaterialIdRoute =
  CreatorBuilderMaterialIdRouteImport.update({
    id: '/builder/material/$id',
    path: '/builder/material/$id',
    getParentRoute: () => CreatorRoute,
  } as any)
const CreatorBuilderCourseIdRoute = CreatorBuilderCourseIdRouteImport.update({
  id: '/builder/course/$id',
  path: '/builder/course/$id',
  getParentRoute: () => CreatorRoute,
} as any)
const CreatorBuilderBookIdRoute = CreatorBuilderBookIdRouteImport.update({
  id: '/builder/book/$id',
  path: '/builder/book/$id',
  getParentRoute: () => CreatorRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/choose-profile': typeof ChooseProfileRoute
  '/creator': typeof CreatorRouteWithChildren
  '/login': typeof LoginRoute
  '/org': typeof OrgRouteWithChildren
  '/reviewer': typeof ReviewerRouteWithChildren
  '/school': typeof SchoolRouteWithChildren
  '/student': typeof StudentRouteWithChildren
  '/admin/channel': typeof AdminChannelRoute
  '/admin/content-review': typeof AdminContentReviewRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/library': typeof AdminLibraryRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/studio': typeof AdminStudioRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/admin/verification-requests': typeof AdminVerificationRequestsRoute
  '/creator/channel': typeof CreatorChannelRouteWithChildren
  '/creator/dashboard': typeof CreatorDashboardRoute
  '/creator/dept-review': typeof CreatorDeptReviewRoute
  '/creator/library': typeof CreatorLibraryRoute
  '/creator/registry': typeof CreatorRegistryRoute
  '/creator/settings': typeof CreatorSettingsRoute
  '/creator/studio': typeof CreatorStudioRouteWithChildren
  '/creator/verification': typeof CreatorVerificationRoute
  '/org/analytics': typeof OrgAnalyticsRoute
  '/org/channel': typeof OrgChannelRouteWithChildren
  '/org/dashboard': typeof OrgDashboardRoute
  '/org/library': typeof OrgLibraryRoute
  '/org/members': typeof OrgMembersRoute
  '/org/settings': typeof OrgSettingsRoute
  '/org/signing': typeof OrgSigningRoute
  '/org/structure': typeof OrgStructureRoute
  '/org/studio': typeof OrgStudioRouteWithChildren
  '/org/verification': typeof OrgVerificationRoute
  '/reviewer/queue': typeof ReviewerQueueRoute
  '/reviewer/reports': typeof ReviewerReportsRoute
  '/school/dashboard': typeof SchoolDashboardRoute
  '/school/review': typeof SchoolReviewRoute
  '/student/explore': typeof StudentExploreRoute
  '/student/home': typeof StudentHomeRoute
  '/student/progress': typeof StudentProgressRoute
  '/creator/channel/edit': typeof CreatorChannelEditRoute
  '/creator/studio/new': typeof CreatorStudioNewRoute
  '/org/channel/edit': typeof OrgChannelEditRoute
  '/org/studio/new': typeof OrgStudioNewRoute
  '/reviewer/review/$id': typeof ReviewerReviewIdRoute
  '/student/learn/$id': typeof StudentLearnIdRoute
  '/creator/builder/book/$id': typeof CreatorBuilderBookIdRoute
  '/creator/builder/course/$id': typeof CreatorBuilderCourseIdRoute
  '/creator/builder/material/$id': typeof CreatorBuilderMaterialIdRoute
  '/creator/builder/quiz/$id': typeof CreatorBuilderQuizIdRoute
  '/org/builder/book/$id': typeof OrgBuilderBookIdRoute
  '/org/builder/course/$id': typeof OrgBuilderCourseIdRoute
  '/org/builder/material/$id': typeof OrgBuilderMaterialIdRoute
  '/org/builder/quiz/$id': typeof OrgBuilderQuizIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/choose-profile': typeof ChooseProfileRoute
  '/creator': typeof CreatorRouteWithChildren
  '/login': typeof LoginRoute
  '/org': typeof OrgRouteWithChildren
  '/reviewer': typeof ReviewerRouteWithChildren
  '/school': typeof SchoolRouteWithChildren
  '/student': typeof StudentRouteWithChildren
  '/admin/channel': typeof AdminChannelRoute
  '/admin/content-review': typeof AdminContentReviewRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/library': typeof AdminLibraryRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/studio': typeof AdminStudioRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/admin/verification-requests': typeof AdminVerificationRequestsRoute
  '/creator/channel': typeof CreatorChannelRouteWithChildren
  '/creator/dashboard': typeof CreatorDashboardRoute
  '/creator/dept-review': typeof CreatorDeptReviewRoute
  '/creator/library': typeof CreatorLibraryRoute
  '/creator/registry': typeof CreatorRegistryRoute
  '/creator/settings': typeof CreatorSettingsRoute
  '/creator/studio': typeof CreatorStudioRouteWithChildren
  '/creator/verification': typeof CreatorVerificationRoute
  '/org/analytics': typeof OrgAnalyticsRoute
  '/org/channel': typeof OrgChannelRouteWithChildren
  '/org/dashboard': typeof OrgDashboardRoute
  '/org/library': typeof OrgLibraryRoute
  '/org/members': typeof OrgMembersRoute
  '/org/settings': typeof OrgSettingsRoute
  '/org/signing': typeof OrgSigningRoute
  '/org/structure': typeof OrgStructureRoute
  '/org/studio': typeof OrgStudioRouteWithChildren
  '/org/verification': typeof OrgVerificationRoute
  '/reviewer/queue': typeof ReviewerQueueRoute
  '/reviewer/reports': typeof ReviewerReportsRoute
  '/school/dashboard': typeof SchoolDashboardRoute
  '/school/review': typeof SchoolReviewRoute
  '/student/explore': typeof StudentExploreRoute
  '/student/home': typeof StudentHomeRoute
  '/student/progress': typeof StudentProgressRoute
  '/creator/channel/edit': typeof CreatorChannelEditRoute
  '/creator/studio/new': typeof CreatorStudioNewRoute
  '/org/channel/edit': typeof OrgChannelEditRoute
  '/org/studio/new': typeof OrgStudioNewRoute
  '/reviewer/review/$id': typeof ReviewerReviewIdRoute
  '/student/learn/$id': typeof StudentLearnIdRoute
  '/creator/builder/book/$id': typeof CreatorBuilderBookIdRoute
  '/creator/builder/course/$id': typeof CreatorBuilderCourseIdRoute
  '/creator/builder/material/$id': typeof CreatorBuilderMaterialIdRoute
  '/creator/builder/quiz/$id': typeof CreatorBuilderQuizIdRoute
  '/org/builder/book/$id': typeof OrgBuilderBookIdRoute
  '/org/builder/course/$id': typeof OrgBuilderCourseIdRoute
  '/org/builder/material/$id': typeof OrgBuilderMaterialIdRoute
  '/org/builder/quiz/$id': typeof OrgBuilderQuizIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/choose-profile': typeof ChooseProfileRoute
  '/creator': typeof CreatorRouteWithChildren
  '/login': typeof LoginRoute
  '/org': typeof OrgRouteWithChildren
  '/reviewer': typeof ReviewerRouteWithChildren
  '/school': typeof SchoolRouteWithChildren
  '/student': typeof StudentRouteWithChildren
  '/admin/channel': typeof AdminChannelRoute
  '/admin/content-review': typeof AdminContentReviewRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/library': typeof AdminLibraryRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/studio': typeof AdminStudioRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/admin/verification-requests': typeof AdminVerificationRequestsRoute
  '/creator/channel': typeof CreatorChannelRouteWithChildren
  '/creator/dashboard': typeof CreatorDashboardRoute
  '/creator/dept-review': typeof CreatorDeptReviewRoute
  '/creator/library': typeof CreatorLibraryRoute
  '/creator/registry': typeof CreatorRegistryRoute
  '/creator/settings': typeof CreatorSettingsRoute
  '/creator/studio': typeof CreatorStudioRouteWithChildren
  '/creator/verification': typeof CreatorVerificationRoute
  '/org/analytics': typeof OrgAnalyticsRoute
  '/org/channel': typeof OrgChannelRouteWithChildren
  '/org/dashboard': typeof OrgDashboardRoute
  '/org/library': typeof OrgLibraryRoute
  '/org/members': typeof OrgMembersRoute
  '/org/settings': typeof OrgSettingsRoute
  '/org/signing': typeof OrgSigningRoute
  '/org/structure': typeof OrgStructureRoute
  '/org/studio': typeof OrgStudioRouteWithChildren
  '/org/verification': typeof OrgVerificationRoute
  '/reviewer/queue': typeof ReviewerQueueRoute
  '/reviewer/reports': typeof ReviewerReportsRoute
  '/school/dashboard': typeof SchoolDashboardRoute
  '/school/review': typeof SchoolReviewRoute
  '/student/explore': typeof StudentExploreRoute
  '/student/home': typeof StudentHomeRoute
  '/student/progress': typeof StudentProgressRoute
  '/creator/channel/edit': typeof CreatorChannelEditRoute
  '/creator/studio/new': typeof CreatorStudioNewRoute
  '/org/channel/edit': typeof OrgChannelEditRoute
  '/org/studio/new': typeof OrgStudioNewRoute
  '/reviewer/review/$id': typeof ReviewerReviewIdRoute
  '/student/learn/$id': typeof StudentLearnIdRoute
  '/creator/builder/book/$id': typeof CreatorBuilderBookIdRoute
  '/creator/builder/course/$id': typeof CreatorBuilderCourseIdRoute
  '/creator/builder/material/$id': typeof CreatorBuilderMaterialIdRoute
  '/creator/builder/quiz/$id': typeof CreatorBuilderQuizIdRoute
  '/org/builder/book/$id': typeof OrgBuilderBookIdRoute
  '/org/builder/course/$id': typeof OrgBuilderCourseIdRoute
  '/org/builder/material/$id': typeof OrgBuilderMaterialIdRoute
  '/org/builder/quiz/$id': typeof OrgBuilderQuizIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/choose-profile'
    | '/creator'
    | '/login'
    | '/org'
    | '/reviewer'
    | '/school'
    | '/student'
    | '/admin/channel'
    | '/admin/content-review'
    | '/admin/dashboard'
    | '/admin/library'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/studio'
    | '/admin/users'
    | '/admin/verification'
    | '/admin/verification-requests'
    | '/creator/channel'
    | '/creator/dashboard'
    | '/creator/dept-review'
    | '/creator/library'
    | '/creator/registry'
    | '/creator/settings'
    | '/creator/studio'
    | '/creator/verification'
    | '/org/analytics'
    | '/org/channel'
    | '/org/dashboard'
    | '/org/library'
    | '/org/members'
    | '/org/settings'
    | '/org/signing'
    | '/org/structure'
    | '/org/studio'
    | '/org/verification'
    | '/reviewer/queue'
    | '/reviewer/reports'
    | '/school/dashboard'
    | '/school/review'
    | '/student/explore'
    | '/student/home'
    | '/student/progress'
    | '/creator/channel/edit'
    | '/creator/studio/new'
    | '/org/channel/edit'
    | '/org/studio/new'
    | '/reviewer/review/$id'
    | '/student/learn/$id'
    | '/creator/builder/book/$id'
    | '/creator/builder/course/$id'
    | '/creator/builder/material/$id'
    | '/creator/builder/quiz/$id'
    | '/org/builder/book/$id'
    | '/org/builder/course/$id'
    | '/org/builder/material/$id'
    | '/org/builder/quiz/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/choose-profile'
    | '/creator'
    | '/login'
    | '/org'
    | '/reviewer'
    | '/school'
    | '/student'
    | '/admin/channel'
    | '/admin/content-review'
    | '/admin/dashboard'
    | '/admin/library'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/studio'
    | '/admin/users'
    | '/admin/verification'
    | '/admin/verification-requests'
    | '/creator/channel'
    | '/creator/dashboard'
    | '/creator/dept-review'
    | '/creator/library'
    | '/creator/registry'
    | '/creator/settings'
    | '/creator/studio'
    | '/creator/verification'
    | '/org/analytics'
    | '/org/channel'
    | '/org/dashboard'
    | '/org/library'
    | '/org/members'
    | '/org/settings'
    | '/org/signing'
    | '/org/structure'
    | '/org/studio'
    | '/org/verification'
    | '/reviewer/queue'
    | '/reviewer/reports'
    | '/school/dashboard'
    | '/school/review'
    | '/student/explore'
    | '/student/home'
    | '/student/progress'
    | '/creator/channel/edit'
    | '/creator/studio/new'
    | '/org/channel/edit'
    | '/org/studio/new'
    | '/reviewer/review/$id'
    | '/student/learn/$id'
    | '/creator/builder/book/$id'
    | '/creator/builder/course/$id'
    | '/creator/builder/material/$id'
    | '/creator/builder/quiz/$id'
    | '/org/builder/book/$id'
    | '/org/builder/course/$id'
    | '/org/builder/material/$id'
    | '/org/builder/quiz/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/choose-profile'
    | '/creator'
    | '/login'
    | '/org'
    | '/reviewer'
    | '/school'
    | '/student'
    | '/admin/channel'
    | '/admin/content-review'
    | '/admin/dashboard'
    | '/admin/library'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/studio'
    | '/admin/users'
    | '/admin/verification'
    | '/admin/verification-requests'
    | '/creator/channel'
    | '/creator/dashboard'
    | '/creator/dept-review'
    | '/creator/library'
    | '/creator/registry'
    | '/creator/settings'
    | '/creator/studio'
    | '/creator/verification'
    | '/org/analytics'
    | '/org/channel'
    | '/org/dashboard'
    | '/org/library'
    | '/org/members'
    | '/org/settings'
    | '/org/signing'
    | '/org/structure'
    | '/org/studio'
    | '/org/verification'
    | '/reviewer/queue'
    | '/reviewer/reports'
    | '/school/dashboard'
    | '/school/review'
    | '/student/explore'
    | '/student/home'
    | '/student/progress'
    | '/creator/channel/edit'
    | '/creator/studio/new'
    | '/org/channel/edit'
    | '/org/studio/new'
    | '/reviewer/review/$id'
    | '/student/learn/$id'
    | '/creator/builder/book/$id'
    | '/creator/builder/course/$id'
    | '/creator/builder/material/$id'
    | '/creator/builder/quiz/$id'
    | '/org/builder/book/$id'
    | '/org/builder/course/$id'
    | '/org/builder/material/$id'
    | '/org/builder/quiz/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ChooseProfileRoute: typeof ChooseProfileRoute
  CreatorRoute: typeof CreatorRouteWithChildren
  LoginRoute: typeof LoginRoute
  OrgRoute: typeof OrgRouteWithChildren
  ReviewerRoute: typeof ReviewerRouteWithChildren
  SchoolRoute: typeof SchoolRouteWithChildren
  StudentRoute: typeof StudentRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/school': {
      id: '/school'
      path: '/school'
      fullPath: '/school'
      preLoaderRoute: typeof SchoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviewer': {
      id: '/reviewer'
      path: '/reviewer'
      fullPath: '/reviewer'
      preLoaderRoute: typeof ReviewerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org': {
      id: '/org'
      path: '/org'
      fullPath: '/org'
      preLoaderRoute: typeof OrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator': {
      id: '/creator'
      path: '/creator'
      fullPath: '/creator'
      preLoaderRoute: typeof CreatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/choose-profile': {
      id: '/choose-profile'
      path: '/choose-profile'
      fullPath: '/choose-profile'
      preLoaderRoute: typeof ChooseProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/progress': {
      id: '/student/progress'
      path: '/progress'
      fullPath: '/student/progress'
      preLoaderRoute: typeof StudentProgressRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/home': {
      id: '/student/home'
      path: '/home'
      fullPath: '/student/home'
      preLoaderRoute: typeof StudentHomeRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/explore': {
      id: '/student/explore'
      path: '/explore'
      fullPath: '/student/explore'
      preLoaderRoute: typeof StudentExploreRouteImport
      parentRoute: typeof StudentRoute
    }
    '/school/review': {
      id: '/school/review'
      path: '/review'
      fullPath: '/school/review'
      preLoaderRoute: typeof SchoolReviewRouteImport
      parentRoute: typeof SchoolRoute
    }
    '/school/dashboard': {
      id: '/school/dashboard'
      path: '/dashboard'
      fullPath: '/school/dashboard'
      preLoaderRoute: typeof SchoolDashboardRouteImport
      parentRoute: typeof SchoolRoute
    }
    '/reviewer/reports': {
      id: '/reviewer/reports'
      path: '/reports'
      fullPath: '/reviewer/reports'
      preLoaderRoute: typeof ReviewerReportsRouteImport
      parentRoute: typeof ReviewerRoute
    }
    '/reviewer/queue': {
      id: '/reviewer/queue'
      path: '/queue'
      fullPath: '/reviewer/queue'
      preLoaderRoute: typeof ReviewerQueueRouteImport
      parentRoute: typeof ReviewerRoute
    }
    '/org/verification': {
      id: '/org/verification'
      path: '/verification'
      fullPath: '/org/verification'
      preLoaderRoute: typeof OrgVerificationRouteImport
      parentRoute: typeof OrgRoute
    }
    '/org/studio': {
      id: '/org/studio'
      path: '/studio'
      fullPath: '/org/studio'
      preLoaderRoute: typeof OrgStudioRouteImport
      parentRoute: typeof OrgRoute
    }
    '/org/structure': {
      id: '/org/structure'
      path: '/structure'
      fullPath: '/org/structure'
      preLoaderRoute: typeof OrgStructureRouteImport
      parentRoute: typeof OrgRoute
    }
    '/org/signing': {
      id: '/org/signing'
      path: '/signing'
      fullPath: '/org/signing'
      preLoaderRoute: typeof OrgSigningRouteImport
      parentRoute: typeof OrgRoute
    }
    '/org/settings': {
      id: '/org/settings'
      path: '/settings'
      fullPath: '/org/settings'
      preLoaderRoute: typeof OrgSettingsRouteImport
      parentRoute: typeof OrgRoute
    }
    '/org/members': {
      id: '/org/members'
      path: '/members'
      fullPath: '/org/members'
      preLoaderRoute: typeof OrgMembersRouteImport
      parentRoute: typeof OrgRoute
    }
    '/org/library': {
      id: '/org/library'
      path: '/library'
      fullPath: '/org/library'
      preLoaderRoute: typeof OrgLibraryRouteImport
      parentRoute: typeof OrgRoute
    }
    '/org/dashboard': {
      id: '/org/dashboard'
      path: '/dashboard'
      fullPath: '/org/dashboard'
      preLoaderRoute: typeof OrgDashboardRouteImport
      parentRoute: typeof OrgRoute
    }
    '/org/channel': {
      id: '/org/channel'
      path: '/channel'
      fullPath: '/org/channel'
      preLoaderRoute: typeof OrgChannelRouteImport
      parentRoute: typeof OrgRoute
    }
    '/org/analytics': {
      id: '/org/analytics'
      path: '/analytics'
      fullPath: '/org/analytics'
      preLoaderRoute: typeof OrgAnalyticsRouteImport
      parentRoute: typeof OrgRoute
    }
    '/creator/verification': {
      id: '/creator/verification'
      path: '/verification'
      fullPath: '/creator/verification'
      preLoaderRoute: typeof CreatorVerificationRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/creator/studio': {
      id: '/creator/studio'
      path: '/studio'
      fullPath: '/creator/studio'
      preLoaderRoute: typeof CreatorStudioRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/creator/settings': {
      id: '/creator/settings'
      path: '/settings'
      fullPath: '/creator/settings'
      preLoaderRoute: typeof CreatorSettingsRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/creator/registry': {
      id: '/creator/registry'
      path: '/registry'
      fullPath: '/creator/registry'
      preLoaderRoute: typeof CreatorRegistryRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/creator/library': {
      id: '/creator/library'
      path: '/library'
      fullPath: '/creator/library'
      preLoaderRoute: typeof CreatorLibraryRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/creator/dept-review': {
      id: '/creator/dept-review'
      path: '/dept-review'
      fullPath: '/creator/dept-review'
      preLoaderRoute: typeof CreatorDeptReviewRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/creator/dashboard': {
      id: '/creator/dashboard'
      path: '/dashboard'
      fullPath: '/creator/dashboard'
      preLoaderRoute: typeof CreatorDashboardRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/creator/channel': {
      id: '/creator/channel'
      path: '/channel'
      fullPath: '/creator/channel'
      preLoaderRoute: typeof CreatorChannelRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/admin/verification-requests': {
      id: '/admin/verification-requests'
      path: '/verification-requests'
      fullPath: '/admin/verification-requests'
      preLoaderRoute: typeof AdminVerificationRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/verification': {
      id: '/admin/verification'
      path: '/verification'
      fullPath: '/admin/verification'
      preLoaderRoute: typeof AdminVerificationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/studio': {
      id: '/admin/studio'
      path: '/studio'
      fullPath: '/admin/studio'
      preLoaderRoute: typeof AdminStudioRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/library': {
      id: '/admin/library'
      path: '/library'
      fullPath: '/admin/library'
      preLoaderRoute: typeof AdminLibraryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content-review': {
      id: '/admin/content-review'
      path: '/content-review'
      fullPath: '/admin/content-review'
      preLoaderRoute: typeof AdminContentReviewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/channel': {
      id: '/admin/channel'
      path: '/channel'
      fullPath: '/admin/channel'
      preLoaderRoute: typeof AdminChannelRouteImport
      parentRoute: typeof AdminRoute
    }
    '/student/learn/$id': {
      id: '/student/learn/$id'
      path: '/learn/$id'
      fullPath: '/student/learn/$id'
      preLoaderRoute: typeof StudentLearnIdRouteImport
      parentRoute: typeof StudentRoute
    }
    '/reviewer/review/$id': {
      id: '/reviewer/review/$id'
      path: '/review/$id'
      fullPath: '/reviewer/review/$id'
      preLoaderRoute: typeof ReviewerReviewIdRouteImport
      parentRoute: typeof ReviewerRoute
    }
    '/org/studio/new': {
      id: '/org/studio/new'
      path: '/new'
      fullPath: '/org/studio/new'
      preLoaderRoute: typeof OrgStudioNewRouteImport
      parentRoute: typeof OrgStudioRoute
    }
    '/org/channel/edit': {
      id: '/org/channel/edit'
      path: '/edit'
      fullPath: '/org/channel/edit'
      preLoaderRoute: typeof OrgChannelEditRouteImport
      parentRoute: typeof OrgChannelRoute
    }
    '/creator/studio/new': {
      id: '/creator/studio/new'
      path: '/new'
      fullPath: '/creator/studio/new'
      preLoaderRoute: typeof CreatorStudioNewRouteImport
      parentRoute: typeof CreatorStudioRoute
    }
    '/creator/channel/edit': {
      id: '/creator/channel/edit'
      path: '/edit'
      fullPath: '/creator/channel/edit'
      preLoaderRoute: typeof CreatorChannelEditRouteImport
      parentRoute: typeof CreatorChannelRoute
    }
    '/org/builder/quiz/$id': {
      id: '/org/builder/quiz/$id'
      path: '/builder/quiz/$id'
      fullPath: '/org/builder/quiz/$id'
      preLoaderRoute: typeof OrgBuilderQuizIdRouteImport
      parentRoute: typeof OrgRoute
    }
    '/org/builder/material/$id': {
      id: '/org/builder/material/$id'
      path: '/builder/material/$id'
      fullPath: '/org/builder/material/$id'
      preLoaderRoute: typeof OrgBuilderMaterialIdRouteImport
      parentRoute: typeof OrgRoute
    }
    '/org/builder/course/$id': {
      id: '/org/builder/course/$id'
      path: '/builder/course/$id'
      fullPath: '/org/builder/course/$id'
      preLoaderRoute: typeof OrgBuilderCourseIdRouteImport
      parentRoute: typeof OrgRoute
    }
    '/org/builder/book/$id': {
      id: '/org/builder/book/$id'
      path: '/builder/book/$id'
      fullPath: '/org/builder/book/$id'
      preLoaderRoute: typeof OrgBuilderBookIdRouteImport
      parentRoute: typeof OrgRoute
    }
    '/creator/builder/quiz/$id': {
      id: '/creator/builder/quiz/$id'
      path: '/builder/quiz/$id'
      fullPath: '/creator/builder/quiz/$id'
      preLoaderRoute: typeof CreatorBuilderQuizIdRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/creator/builder/material/$id': {
      id: '/creator/builder/material/$id'
      path: '/builder/material/$id'
      fullPath: '/creator/builder/material/$id'
      preLoaderRoute: typeof CreatorBuilderMaterialIdRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/creator/builder/course/$id': {
      id: '/creator/builder/course/$id'
      path: '/builder/course/$id'
      fullPath: '/creator/builder/course/$id'
      preLoaderRoute: typeof CreatorBuilderCourseIdRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/creator/builder/book/$id': {
      id: '/creator/builder/book/$id'
      path: '/builder/book/$id'
      fullPath: '/creator/builder/book/$id'
      preLoaderRoute: typeof CreatorBuilderBookIdRouteImport
      parentRoute: typeof CreatorRoute
    }
  }
}

interface AdminRouteChildren {
  AdminChannelRoute: typeof AdminChannelRoute
  AdminContentReviewRoute: typeof AdminContentReviewRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLibraryRoute: typeof AdminLibraryRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStudioRoute: typeof AdminStudioRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVerificationRoute: typeof AdminVerificationRoute
  AdminVerificationRequestsRoute: typeof AdminVerificationRequestsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminChannelRoute: AdminChannelRoute,
  AdminContentReviewRoute: AdminContentReviewRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLibraryRoute: AdminLibraryRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStudioRoute: AdminStudioRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVerificationRoute: AdminVerificationRoute,
  AdminVerificationRequestsRoute: AdminVerificationRequestsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CreatorChannelRouteChildren {
  CreatorChannelEditRoute: typeof CreatorChannelEditRoute
}

const CreatorChannelRouteChildren: CreatorChannelRouteChildren = {
  CreatorChannelEditRoute: CreatorChannelEditRoute,
}

const CreatorChannelRouteWithChildren = CreatorChannelRoute._addFileChildren(
  CreatorChannelRouteChildren,
)

interface CreatorStudioRouteChildren {
  CreatorStudioNewRoute: typeof CreatorStudioNewRoute
}

const CreatorStudioRouteChildren: CreatorStudioRouteChildren = {
  CreatorStudioNewRoute: CreatorStudioNewRoute,
}

const CreatorStudioRouteWithChildren = CreatorStudioRoute._addFileChildren(
  CreatorStudioRouteChildren,
)

interface CreatorRouteChildren {
  CreatorChannelRoute: typeof CreatorChannelRouteWithChildren
  CreatorDashboardRoute: typeof CreatorDashboardRoute
  CreatorDeptReviewRoute: typeof CreatorDeptReviewRoute
  CreatorLibraryRoute: typeof CreatorLibraryRoute
  CreatorRegistryRoute: typeof CreatorRegistryRoute
  CreatorSettingsRoute: typeof CreatorSettingsRoute
  CreatorStudioRoute: typeof CreatorStudioRouteWithChildren
  CreatorVerificationRoute: typeof CreatorVerificationRoute
  CreatorBuilderBookIdRoute: typeof CreatorBuilderBookIdRoute
  CreatorBuilderCourseIdRoute: typeof CreatorBuilderCourseIdRoute
  CreatorBuilderMaterialIdRoute: typeof CreatorBuilderMaterialIdRoute
  CreatorBuilderQuizIdRoute: typeof CreatorBuilderQuizIdRoute
}

const CreatorRouteChildren: CreatorRouteChildren = {
  CreatorChannelRoute: CreatorChannelRouteWithChildren,
  CreatorDashboardRoute: CreatorDashboardRoute,
  CreatorDeptReviewRoute: CreatorDeptReviewRoute,
  CreatorLibraryRoute: CreatorLibraryRoute,
  CreatorRegistryRoute: CreatorRegistryRoute,
  CreatorSettingsRoute: CreatorSettingsRoute,
  CreatorStudioRoute: CreatorStudioRouteWithChildren,
  CreatorVerificationRoute: CreatorVerificationRoute,
  CreatorBuilderBookIdRoute: CreatorBuilderBookIdRoute,
  CreatorBuilderCourseIdRoute: CreatorBuilderCourseIdRoute,
  CreatorBuilderMaterialIdRoute: CreatorBuilderMaterialIdRoute,
  CreatorBuilderQuizIdRoute: CreatorBuilderQuizIdRoute,
}

const CreatorRouteWithChildren =
  CreatorRoute._addFileChildren(CreatorRouteChildren)

interface OrgChannelRouteChildren {
  OrgChannelEditRoute: typeof OrgChannelEditRoute
}

const OrgChannelRouteChildren: OrgChannelRouteChildren = {
  OrgChannelEditRoute: OrgChannelEditRoute,
}

const OrgChannelRouteWithChildren = OrgChannelRoute._addFileChildren(
  OrgChannelRouteChildren,
)

interface OrgStudioRouteChildren {
  OrgStudioNewRoute: typeof OrgStudioNewRoute
}

const OrgStudioRouteChildren: OrgStudioRouteChildren = {
  OrgStudioNewRoute: OrgStudioNewRoute,
}

const OrgStudioRouteWithChildren = OrgStudioRoute._addFileChildren(
  OrgStudioRouteChildren,
)

interface OrgRouteChildren {
  OrgAnalyticsRoute: typeof OrgAnalyticsRoute
  OrgChannelRoute: typeof OrgChannelRouteWithChildren
  OrgDashboardRoute: typeof OrgDashboardRoute
  OrgLibraryRoute: typeof OrgLibraryRoute
  OrgMembersRoute: typeof OrgMembersRoute
  OrgSettingsRoute: typeof OrgSettingsRoute
  OrgSigningRoute: typeof OrgSigningRoute
  OrgStructureRoute: typeof OrgStructureRoute
  OrgStudioRoute: typeof OrgStudioRouteWithChildren
  OrgVerificationRoute: typeof OrgVerificationRoute
  OrgBuilderBookIdRoute: typeof OrgBuilderBookIdRoute
  OrgBuilderCourseIdRoute: typeof OrgBuilderCourseIdRoute
  OrgBuilderMaterialIdRoute: typeof OrgBuilderMaterialIdRoute
  OrgBuilderQuizIdRoute: typeof OrgBuilderQuizIdRoute
}

const OrgRouteChildren: OrgRouteChildren = {
  OrgAnalyticsRoute: OrgAnalyticsRoute,
  OrgChannelRoute: OrgChannelRouteWithChildren,
  OrgDashboardRoute: OrgDashboardRoute,
  OrgLibraryRoute: OrgLibraryRoute,
  OrgMembersRoute: OrgMembersRoute,
  OrgSettingsRoute: OrgSettingsRoute,
  OrgSigningRoute: OrgSigningRoute,
  OrgStructureRoute: OrgStructureRoute,
  OrgStudioRoute: OrgStudioRouteWithChildren,
  OrgVerificationRoute: OrgVerificationRoute,
  OrgBuilderBookIdRoute: OrgBuilderBookIdRoute,
  OrgBuilderCourseIdRoute: OrgBuilderCourseIdRoute,
  OrgBuilderMaterialIdRoute: OrgBuilderMaterialIdRoute,
  OrgBuilderQuizIdRoute: OrgBuilderQuizIdRoute,
}

const OrgRouteWithChildren = OrgRoute._addFileChildren(OrgRouteChildren)

interface ReviewerRouteChildren {
  ReviewerQueueRoute: typeof ReviewerQueueRoute
  ReviewerReportsRoute: typeof ReviewerReportsRoute
  ReviewerReviewIdRoute: typeof ReviewerReviewIdRoute
}

const ReviewerRouteChildren: ReviewerRouteChildren = {
  ReviewerQueueRoute: ReviewerQueueRoute,
  ReviewerReportsRoute: ReviewerReportsRoute,
  ReviewerReviewIdRoute: ReviewerReviewIdRoute,
}

const ReviewerRouteWithChildren = ReviewerRoute._addFileChildren(
  ReviewerRouteChildren,
)

interface SchoolRouteChildren {
  SchoolDashboardRoute: typeof SchoolDashboardRoute
  SchoolReviewRoute: typeof SchoolReviewRoute
}

const SchoolRouteChildren: SchoolRouteChildren = {
  SchoolDashboardRoute: SchoolDashboardRoute,
  SchoolReviewRoute: SchoolReviewRoute,
}

const SchoolRouteWithChildren =
  SchoolRoute._addFileChildren(SchoolRouteChildren)

interface StudentRouteChildren {
  StudentExploreRoute: typeof StudentExploreRoute
  StudentHomeRoute: typeof StudentHomeRoute
  StudentProgressRoute: typeof StudentProgressRoute
  StudentLearnIdRoute: typeof StudentLearnIdRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentExploreRoute: StudentExploreRoute,
  StudentHomeRoute: StudentHomeRoute,
  StudentProgressRoute: StudentProgressRoute,
  StudentLearnIdRoute: StudentLearnIdRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ChooseProfileRoute: ChooseProfileRoute,
  CreatorRoute: CreatorRouteWithChildren,
  LoginRoute: LoginRoute,
  OrgRoute: OrgRouteWithChildren,
  ReviewerRoute: ReviewerRouteWithChildren,
  SchoolRoute: SchoolRouteWithChildren,
  StudentRoute: StudentRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
